### ISSUE TITLE
FunctionClauseError on db shutdown

### ISSUE THREAD

**Issue by Mazyod** [elixir-ecto/postgrex#266]
Hey everyone,

When running a simple elixir app that only has ecto, postgrex, poison as dependencies, I am getting a `FunctionClauseError` when I terminate the DB. I am guessing that error in question is not helpful to the developer, hence is a possible bug.

Please note I am not performing any kind of app specific logic. My supervision tree only has the `Repo` and one idle `GenServer` worker.

I've seen this on my Ubuntu 14.04 server, and replicated it with my El Capitan machine. My postgres version is 9.6.1, server uses 9.5.4. Finally, I updated to `ecto 2.1-rc`, got the same issue.

```
07:14:29.908 [error] GenServer #PID<0.181.0> terminating
** (FunctionClauseError) no function clause matching in Postgrex.Protocol.handle_msg/3
    (postgrex) lib/postgrex/protocol.ex:1765: Postgrex.Protocol.handle_msg(%Postgrex.Protocol{buffer: nil, connection_id: 58195, connection_key: 194376013, null: nil, parameters: #Reference<0.0.3.554>, peer: {{127, 0, 0, 1}, 5432}, postgres: :idle, queries: 143402, sock: {:gen_tcp, #Port<0.5230>}, timeout: 15000, transactions: :naive, types: 131111}, %{mode: :transaction, notify: #Function<46.116520996/2 in Postgrex.Protocol.notify/1>, sync: :sync}, {:msg_error, [severity: "FATAL", unknown: "FATAL", code: "57P01", message: "terminating connection due to unexpected postmaster exit", file: "be-secure.c", line: "171", routine: "secure_read"]})
    (postgrex) lib/postgrex/protocol.ex:1880: Postgrex.Protocol.do_sync_recv/4
    (db_connection) lib/db_connection/connection.ex:358: DBConnection.Connection.handle_info/2
    (connection) lib/connection.ex:810: Connection.handle_async/3
    (stdlib) gen_server.erl:601: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:667: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: :timeout
State: {Postgrex.Protocol, %Postgrex.Protocol{buffer: "", connection_id: 58195, connection_key: 194376013, null: nil, parameters: #Reference<0.0.3.554>, peer: {{127, 0, 0, 1}, 5432}, postgres: :idle, queries: 143402, sock: {:gen_tcp, #Port<0.5230>}, timeout: 15000, transactions: :naive, types: 131111}}
```

mix.lock

```
%{"connection": {:hex, :connection, "1.0.4", "a1cae72211f0eef17705aaededacac3eb30e6625b04a6117c1b2db6ace7d5976", [:mix], []},
  "db_connection": {:hex, :db_connection, "1.1.0", "b2b88db6d7d12f99997b584d09fad98e560b817a20dab6a526830e339f54cdb3", [:mix], [{:connection, "~> 1.0.2", [hex: :connection, optional: false]}, {:poolboy, "~> 1.5", [hex: :poolboy, optional: true]}, {:sbroker, "~> 1.0", [hex: :sbroker, optional: true]}]},
  "decimal": {:hex, :decimal, "1.3.1", "157b3cedb2bfcb5359372a7766dd7a41091ad34578296e951f58a946fcab49c6", [:mix], []},
  "ecto": {:hex, :ecto, "2.0.5", "7f4c79ac41ffba1a4c032b69d7045489f0069c256de606523c65d9f8188e502d", [:mix], [{:db_connection, "~> 1.0-rc.4", [hex: :db_connection, optional: true]}, {:decimal, "~> 1.1.2 or ~> 1.2", [hex: :decimal, optional: false]}, {:mariaex, "~> 0.7.7", [hex: :mariaex, optional: true]}, {:poison, "~> 1.5 or ~> 2.0", [hex: :poison, optional: true]}, {:poolboy, "~> 1.5", [hex: :poolboy, optional: false]}, {:postgrex, "~> 0.12.0", [hex: :postgrex, optional: true]}, {:sbroker, "~> 1.0-beta", [hex: :sbroker, optional: true]}]},
  "erlport": {:git, "https://github.com/hdima/erlport.git", "246b7722d62b87b48be66d9a871509a537728962", []},
  "poison": {:hex, :poison, "2.2.0", "4763b69a8a77bd77d26f477d196428b741261a761257ff1cf92753a0d4d24a63", [:mix], []},
  "poolboy": {:hex, :poolboy, "1.5.1", "6b46163901cfd0a1b43d692657ed9d7e599853b3b21b95ae5ae0a777cf9b6ca8", [:rebar], []},
  "postgrex": {:hex, :postgrex, "0.12.1", "2f8b46cb3a44dcd42f42938abedbfffe7e103ba4ce810ccbeee8dcf27ca0fb06", [:mix], [{:connection, "~> 1.0", [hex: :connection, optional: false]}, {:db_connection, "~> 1.0-rc.4", [hex: :db_connection, optional: false]}, {:decimal, "~> 1.0", [hex: :decimal, optional: false]}]},
  "skillz": {:git, "https://github.com/mazyod/skillz.git", "5abae830efd6f9ab9d67531e28c432271ce43f92", []}}
```

#### Background

Throughout my research for DBs as  a service, I've found that many services, including amazon RDS, need to take the DB offline for maintenance (OS, security updates, .. etc). That is unless you have high availability setup, of course, but unfortunately, my budget doesn't stretch that far.

So, I'm investing some time in testing the edge case where the DB just goes offline, and monitoring how my application reacts to that.

**Comment by fishcakez** [comment]
Is this fixed in https://github.com/elixir-ecto/postgrex/commit/2282baf7ad476960499799d432296fed87d3c62b? I think should be able to backport.

**Comment by Mazyod** [comment]
@fishcakez I can't get the dependency between postgrex rc release and ecto to work out, in order to test

**Comment by fishcakez** [comment]
@Mazyod https://github.com/fishcakez/postgrex/tree/mayzod

**Comment by fishcakez** [comment]
Ah sorry spelt name wrong in branch :(

**Comment by Mazyod** [comment]
Hey, I can't seem to pull th– ... oh ¯\_(ツ)_/¯

👍 Can't reproduce. Thanks!
