### ISSUE TITLE
Cant connect to Postgres after update

### ISSUE THREAD

**Issue by madshargreave** [elixir-ecto/postgrex#268]
I am trying to update ecto and postgrex to use PG9.6

These are my deps

```
elixir: "~> 1.3.0",

defp deps do
    [{:phoenix, "~> 1.2.0", override: true},
     {:phoenix_ecto, "~> 3.1.0-rc.0"},
     {:ecto, "2.1.0-rc.4"},
     {:postgrex, ">= 1.0.0-rc.1"},
```

After the update and I deploy to a staging server using this config

```
config :resend, Resend.Repo,
  adapter: Ecto.Adapters.Postgres,
  url: System.get_env("DATABASE_URL"),
  pool_size: 3,
```

I get the following error in an infinite loop:
```
 (elixir) lib/keyword.ex:333: Keyword.fetch!/2
2016-12-03T20:28:34.559691335Z app[web.1]:     (postgrex) lib/postgrex/protocol.ex:80: Postgrex.Protocol.connect/1
2016-12-03T20:28:34.559695845Z app[web.1]:     (db_connection) lib/db_connection/connection.ex:134: DBConnection.Connection.connect/2
2016-12-03T20:28:34.559700584Z app[web.1]:     (connection) lib/connection.ex:622: Connection.enter_connect/5
2016-12-03T20:28:34.559705187Z app[web.1]:     (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
2016-12-03T20:28:34.559709734Z app[web.1]: Last message: nil
2016-12-03T20:28:34.559714185Z app[web.1]: State: Postgrex.Protocol
2016-12-03T20:28:34.560216846Z app[web.1]: [error] GenServer #PID<0.22272.19> terminating
2016-12-03T20:28:34.560240913Z app[web.1]: ** (KeyError) key :database not found in: [types: true, hostname: "localhost", username: "herokuishuser", types: true, port: 5432, name: Resend.Repo.Pool, otp_app: :resend, repo: Resend.Repo, adapter: Ecto.Adapters.Postgres, pool_size: 3, pool_timeout: 5000, timeout: 15000, adapter: Ecto.Adapters.Postgres, pool_size: 3, pool: DBConnection.Poolboy, extensions: [{Ecto.Adapters.Postgres.DateTime, []}, {Postgrex.Extensions.JSON, [library: Poison]}]]

```

I haven't been able to find documentation on such a breaking change, have I missed something?

**Comment by fishcakez** [comment]
Postgrex isn't getting the database from Ecto so I'm not it is an issue in postgrex. Have you checked the `DATABASE_URL`?

**Comment by madshargreave** [comment]
You're exactly right, there was an error in the URL - Sorry about that, but thanks!
