### ISSUE TITLE
Postgrex handling of a termination from server message

### ISSUE THREAD

**Issue by meadoch1** [elixir-ecto/postgrex#281]
We are currently using Elixir 1.3.2, Postgrex 0.12.1, and Ecto 2.0.5.  During some recent PostgreSQL server maintenance, when the dba took the database server down we received the following error.

````
GenServer #PID<0.1862.0> terminating
** (FunctionClauseError) no function clause matching in Postgrex.Protocol.handle_msg/3
    (postgrex) lib/postgrex/protocol.ex:1765: Postgrex.Protocol.handle_msg(%Postgrex.Protocol{buffer: nil, connection_id: 11308, connection_key: 924496271, null: nil, parameters: #Reference<0.0.1.571>, peer: {{192, 168, 28, 175}, 5432}, postgres: :idle, queries: 90187, sock: {:ssl, {:sslsocket, {:gen_tcp, #Port<0.4664>, :tls_connection, :undefined}, #PID<0.1876.0>}}, timeout: 15000, transactions: :naive, types: 61508}, %{mode: :transaction, notify: #Function<46.118565229/2 in Postgrex.Protocol.notify/1>, sync: :sync}, {:msg_error, [severity: "FATAL", code: "57P01", message: "terminating connection due to administrator command", file: "postgres.c", line: "2872", routine: "ProcessInterrupts"]})
    (postgrex) lib/postgrex/protocol.ex:1880: Postgrex.Protocol.do_sync_recv/4
    (db_connection) lib/db_connection/connection.ex:358: DBConnection.Connection.handle_info/2
````

Is this expected or should Postgrex handle this condition more gracefully?

**Comment by fishcakez** [comment]
Please see https://github.com/elixir-ecto/postgrex/issues/266. There is a backported branch and a link to fix commit.
