### ISSUE TITLE
Error message when using an array in a migration without specifying the type could be improved

### ISSUE THREAD

**Issue by almielczarek** [elixir-ecto/postgrex#314]
Given the following code:

```
defmodule EctoTest.Repo.Migrations.CreateTodoList do
  use Ecto.Migration

  def change do
    create table(:todo_list) do
      add :name, :string
      add :items, :array
    end
  end
end
```

The compiler spits out this error:

```
18:18:18.790 [info]  == Running EctoTest.Repo.Migrations.CreateTodoList.change/0 forward

18:18:18.790 [info]  create table todo_list
** (Postgrex.Error) ERROR 42601 (syntax_error): syntax error at or near "array"
    (ecto) lib/ecto/adapters/sql.ex:195: Ecto.Adapters.SQL.query!/5
    (ecto) lib/ecto/adapters/postgres.ex:86: anonymous fn/4 in Ecto.Adapters.Postgres.execute_ddl/3
    (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto) lib/ecto/adapters/postgres.ex:86: Ecto.Adapters.Postgres.execute_ddl/3
    (ecto) lib/ecto/migration/runner.ex:98: anonymous fn/2 in Ecto.Migration.Runner.flush/0
    (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto) lib/ecto/migration/runner.ex:96: Ecto.Migration.Runner.flush/0
    (stdlib) timer.erl:181: :timer.tc/2
```

I think in this case ecto should raise saying something along the lines of "When using the `array` type the type of its elements must also be supplied. Example: `add :list, {:array, :string}`"

**Comment by ericmj** [comment]
This is an ecto issue so please reopen on the ecto project. But I don't think we can raise in ecto in this case since ecto should support custom types and we don't know what types have been defined for the database.

**Comment by josevalim** [comment]
@ericmj the adapter could raise.

@almielczarek yes, please reopen this on the Ecto side. :)
