### ISSUE TITLE
Postgrex internal error after updating to PostgreSQL 10.0

### ISSUE THREAD

**Issue by jrichocean** [elixir-ecto/postgrex#338]
When trying to run migrations I get an error on the migration where im creating a postgres function for a trigger. 

psql version: 10.0
elixir version: 1.5.2
postgrex version: 0.13.3

The migration that fails looks like this -> 
```
defmodule App.Repo.Migrations.AddsNotifyFunction do
  use Ecto.Migration

  def up do
    execute """
    CREATE OR REPLACE FUNCTION notify_foo_changes()
    RETURNS trigger AS $$
    DECLARE
      current_row RECORD;
    BEGIN
      IF (TG_OP = 'INSERT' OR TG_OP = 'UPDATE') THEN
        current_row := NEW;
      ELSE
        current_row := OLD;
      END IF;
      PERFORM pg_notify(
        'foo_changes',
        json_build_object(
          'table', TG_TABLE_NAME,
          'type', TG_OP,
          'id', current_row.id,
          'data', row_to_json(current_row)
        )::text
      );
      RETURN current_row;
    END;
    $$ LANGUAGE plpgsql;
    """

    execute """
    CREATE TRIGGER notify_foo_changes_trg
    AFTER INSERT OR UPDATE OR DELETE
    ON foo
    FOR EACH ROW
    EXECUTE PROCEDURE notify_foo_changes();
    """
  end

  def down do
    execute """
    DROP TRIGGER IF EXISTS notify_foo_changes_trg
    ON credit_cards
    """

    execute """
    DROP FUNCTION IF EXISTS notify_foo_changes()
    """
  end
end
``` 

and the error that is output when running migrations is this ->

```
** (Postgrex.Error) ERROR XX000 (internal_error): could not load library "/usr/local/lib/postgresql/plpgsql.so": dlopen(/usr/local/lib/postgresql/plpgsql.so, 10): Symbol not found: _SPI_register_trigger_data
  Referenced from: /usr/local/lib/postgresql/plpgsql.so
  Expected in: /usr/local/opt/postgresql/bin/postgres
 in /usr/local/lib/postgresql/plpgsql.so
    (ecto) lib/ecto/adapters/sql.ex:195: Ecto.Adapters.SQL.query!/5
    (ecto) lib/ecto/adapters/postgres.ex:85: anonymous fn/4 in Ecto.Adapters.Postgres.execute_ddl/3
    (elixir) lib/enum.ex:1826: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto) lib/ecto/adapters/postgres.ex:85: Ecto.Adapters.Postgres.execute_ddl/3
    (ecto) lib/ecto/migration/runner.ex:98: anonymous fn/2 in Ecto.Migration.Runner.flush/0
    (elixir) lib/enum.ex:1826: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto) lib/ecto/migration/runner.ex:96: Ecto.Migration.Runner.flush/0
    (stdlib) timer.erl:181: :timer.tc/2
    (ecto) lib/ecto/migration/runner.ex:27: Ecto.Migration.Runner.run/6
    (ecto) lib/ecto/migrator.ex:127: Ecto.Migrator.attempt/6
    (ecto) lib/ecto/migrator.ex:72: anonymous fn/4 in Ecto.Migrator.do_up/4
    (ecto) lib/ecto/adapters/sql.ex:620: anonymous fn/3 in Ecto.Adapters.SQL.do_transaction/3
    (db_connection) lib/db_connection.ex:1275: DBConnection.transaction_run/4
    (db_connection) lib/db_connection.ex:1199: DBConnection.run_begin/3
    (db_connection) lib/db_connection.ex:790: DBConnection.transaction/3
    (ecto) lib/ecto/migrator.ex:259: anonymous fn/4 in Ecto.Migrator.migrate/4
    (elixir) lib/enum.ex:1270: Enum."-map/2-lists^map/1-0-"/2
    (elixir) lib/enum.ex:1270: Enum."-map/2-lists^map/1-0-"/2
    (ecto) lib/mix/tasks/ecto.migrate.ex:84: anonymous fn/4 in Mix.Tasks.Ecto.Migrate.run/2
    (elixir) lib/enum.ex:675: Enum."-each/2-lists^foreach/1-0-"/2
```

**Comment by josevalim** [comment]
Please see #335. it is likely an issue with your installation and not Postgrex/Ecto.

**Comment by jrichocean** [comment]
thanks
