### ISSUE TITLE
Implement PostgreSQL peer authentication mechanism

### ISSUE THREAD

**Issue by art-solopov** [elixir-ecto/postgrex#356]
Right now, as far as I understand (according to [start_link/1 documentation](https://hexdocs.pm/postgrex/Postgrex.html#start_link/1)), postgrex only support authentication with password. If the password is not available, `start_link/1` throws an error.

Please do consider supporting PostgreSQL passwordless authentication, such as peer authentication (as do most other drivers). It's convenient for development, and useful for small production and/or staging servers.

**Comment by ericmj** [comment]
Can you show the error that is thrown?

**Comment by art-solopov** [comment]
Here's the error:

```
iex(2)> Postgrex.start_link(database: "elx_simple_api")
{:ok, #PID<0.164.0>}
** (EXIT from #PID<0.161.0>) evaluator process exited with reason: an exception was raised:
    ** (KeyError) key :password not found in: [types: Postgrex.DefaultTypes, hostname: "localhost", username: "art-solopov", database: "elx_simple_api"]
        (elixir) lib/keyword.ex:371: Keyword.fetch!/2
        lib/postgrex/protocol.ex:581: Postgrex.Protocol.auth_md5/4
        lib/postgrex/protocol.ex:475: Postgrex.Protocol.handshake/2
        lib/db_connection/connection.ex:134: DBConnection.Connection.connect/2
        lib/connection.ex:622: Connection.enter_connect/5
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
        
Interactive Elixir (1.5.2) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> 
22:46:45.005 [error] GenServer #PID<0.164.0> terminating
** (KeyError) key :password not found in: [types: Postgrex.DefaultTypes, hostname: "localhost", username: "art-solopov", database: "elx_simple_api"]
    (elixir) lib/keyword.ex:371: Keyword.fetch!/2
    lib/postgrex/protocol.ex:581: Postgrex.Protocol.auth_md5/4
    lib/postgrex/protocol.ex:475: Postgrex.Protocol.handshake/2
    lib/db_connection/connection.ex:134: DBConnection.Connection.connect/2
    lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol
```

**Comment by ericmj** [comment]
If you get this error it means you have configured your server to accept peer authentication for this connection. Can you show your `pg_hba.conf` file?

**Comment by art-solopov** [comment]
If I recall correctly, it's pretty standard `pg_hba` configuration.

```
# Database administrative login by Unix domain socket
local   all             postgres                                peer

# TYPE  DATABASE        USER            ADDRESS                 METHOD

# "local" is for Unix domain socket connections only
local   all             all                                     peer
# IPv4 local connections:
host    all             all             127.0.0.1/32            md5
# IPv6 local connections:
host    all             all             ::1/128                 md5
```

**Comment by ericmj** [comment]
It seems that peer authentication is only enabled for unix sockets in your configuration. Postgrex uses TCP sockets by default and we only have support for unix sockets in master. If you want to try master here is an example of how to connect using unix sockets: https://github.com/elixir-ecto/postgrex/blob/9d042dfa9563fa6739f3e961068b15da3652ae2f/test/login_test.exs#L144-L152

**Comment by art-solopov** [comment]
I see, thank you! Glad it's in the master already!
