### ISSUE TITLE
Postgrex crashes on Postgres' OOM

### ISSUE THREAD

**Issue by aerosol** [elixir-ecto/postgrex#363]
```
** (Postgrex.Error) ERROR 53200 (out_of_memory): out of memory 
Failed on request of size 2048. 
        (ecto) lib/ecto/adapters/sql.ex:445: Ecto.Adapters.SQL.execute_or_reset/7 
        (ecto) lib/ecto/repo/queryable.ex:130: Ecto.Repo.Queryable.execute/5 
        (ecto) lib/ecto/repo/queryable.ex:35: Ecto.Repo.Queryable.all/4 
        (ecto) lib/ecto/repo/preloader.ex:171: Ecto.Repo.Preloader.fetch_query/8 
        (ecto) lib/ecto/repo/preloader.ex:111: Ecto.Repo.Preloader.preload_assoc/10 
        (elixir) lib/task/supervised.ex:85: Task.Supervised.do_apply/2 
        (elixir) lib/task/supervised.ex:36: Task.Supervised.reply/5 
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3 
15:01:22.718 [error] GenServer #PID<0.496.0> terminating 
** (CaseClauseError) no case clause matching: {:ok, "E"} 
    (postgrex) lib/postgrex/protocol.ex:525: Postgrex.Protocol.ssl_recv/2 
    (postgrex) lib/postgrex/protocol.ex:475: Postgrex.Protocol.handshake/2 
    (db_connection) lib/db_connection/connection.ex:134: DBConnection.Connection.connect/2 
    (connection) lib/connection.ex:741: Connection.connect/3 
    (stdlib) gen_server.erl:601: :gen_server.try_dispatch/4 
    (stdlib) gen_server.erl:667: :gen_server.handle_msg/5 
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3 
Last message: {:DOWN, #Reference<0.0.24641538.243800>, :process, #PID<0.18964.21>, {%Postgrex.Error{connection_id: 15359, message: nil, postgres: %{code: :out_of_memory, detail: "Failed on request of size 2048.", file: "mcxt.c", line: "768", message: "out of memory", pg_code: "53200", routine: "MemoryContextAlloc", severity: "ERROR", unknown: "ERROR"}}, [{Ecto.Adapters.SQL, :execute_or_reset, 7, [file: 'lib/ecto/adapters/sql.ex', line: 445]}, {Ecto.Repo.Queryable, :execute, 5, [file: 'lib/ecto/repo/queryable.ex', line: 130]}, {Ecto.Repo.Queryable, :all, 4, [file: 'lib/ecto/repo/queryable.ex', line: 35]}, {Ecto.Repo.Preloader, :fetch_query, 8, [file: 'lib/ecto/repo/preloader.ex', line: 171]}, {Ecto.Repo.Preloader, :preload_assoc, 10, [file: 'lib/ecto/repo/preloader.ex', line: 111]}, {Task.Supervised, :do_apply, 2, [file: 'lib/task/supervised.ex', line: 85]}, {Task.Supervised, :reply, 5, [file: 'lib/task/supervised.ex', line: 36]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]}} 
```

@fishcakez Hi, is lack of the appropriate case clause intentional?

edit: I'm on 0.13.3

**Comment by michalmuskala** [comment]
It looks to me like the omission is accidental. Looking at the postgres documentation, it says:

> The frontend should also be prepared to handle an ErrorMessage response to SSLRequest from the server. This would only occur if the server predates the addition of SSL support to PostgreSQL. (Such servers are now very ancient, and likely do not exist in the wild anymore.) In this case the connection must be closed, but the frontend might choose to open a fresh connection and proceed without requesting SSL.

What postgresql version are you using?

**Comment by aerosol** [comment]
@michalmuskala 9.6.5

**Comment by aerosol** [comment]
Interesting quote. As a side note, this is a fairly new Heroku pg instance (created Oct 2017). Far from "unlikely to exist in the wild" 🤔
