### ISSUE TITLE
Cant Connect to database in docker

### ISSUE THREAD

**Issue by mdramos** [elixir-ecto/postgrex#398]
Runs fine on localhost, but im trying to build a release image with docker and am running into issues when running. Im also running minikube.

docker command:
```
docker run -it -p 8000:8000 -e “HOST=example.com” -e “SECRET_KEY_BASE=highlysecretkey” -e “DB_USERNAME=postgres” -e “DB_PASSWORD=postgres” -e “DB_NAME=myapp_dev” -e “DB_HOSTNAME=10.0.2.2” — rm myapp:release foreground
```

stack:
```
20:30:45.281 [error] GenServer #PID<0.30026.0> terminating
** (ArgumentError) argument error
    (kernel) gen_tcp.erl:153: :gen_tcp.connect/4
    (postgrex) lib/postgrex/protocol.ex:473: Postgrex.Protocol.connect/5
    (postgrex) lib/postgrex/protocol.ex:103: Postgrex.Protocol.connect/1
    (db_connection) lib/db_connection/connection.ex:135: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
```

dep:
```
  defp deps do
    [
       ...
      {:postgrex, ">= 0.13.5"}
      ...
    ]
  end
```

dockerfile:
```
# build
FROM elixir:1.7.2 AS builder
ENV DEBIAN_FRONTEND=noninteractive
ENV HOME=/app/ TERM=xterm
# Install Hex+Rebar
RUN mix local.hex --force && \
    mix local.rebar --force
WORKDIR /app
ENV MIX_ENV=prod REPLACE_OS_VARS=true
# Cache elixir deps
COPY mix.exs mix.lock ./
RUN mix deps.get
COPY config ./config
RUN mix deps.compile
COPY . .
RUN mix release --env=prod

# release
FROM elixir:1.7.2
ENV DEBIAN_FRONTEND=noninteractive
EXPOSE 8000
ENV PORT=8000 MIX_ENV=prod REPLACE_OS_VARS=true SHELL=/bin/bash
WORKDIR /app
COPY --from=builder /app/_build/prod/rel/myapp .

ENTRYPOINT ["bin/myapp"]
```

**Comment by macbem** [comment]
How did you resolve this? I'm facing the exact same issue.

**Comment by Ch4s3** [comment]
I'm running into this issue as well, a solution would be helpful.

**Comment by pejrich** [comment]
Still having this issue. Anyone find a work around?

**Comment by nodeit** [comment]
For anyone who runs into this issue, check your environment variables and configuration parameters closely. I had a blank space at the end of my hostname and it was throwing this error.
