### ISSUE TITLE
Issue parsing version in Postgres 10

### ISSUE THREAD

**Issue by anthonator** [elixir-ecto/postgrex#399]
ref https://github.com/elixir-ecto/ecto/issues/2675

### Environment

Elixir version (elixir -v): 1.7.3
Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 10.5
Ecto version (mix deps): 3.0.0-dev
Database adapter and version (mix deps): Postgrex 0.14.0-dev
Operating system:
```
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
```

### Problem

Seeing this error when trying to run ecto integration tests.

```
19:15:24.555 [error] GenServer #PID<0.249.0> terminating
** (ArgumentError) argument error
    :erlang.element(1, :error)
    (postgrex) lib/postgrex/utils.ex:66: anonymous fn/1 in Postgrex.Utils.parse_version/1
    (elixir) lib/enum.ex:1314: Enum."-map/2-lists^map/1-0-"/2
    (elixir) lib/enum.ex:1314: Enum."-map/2-lists^map/1-0-"/2
    (postgrex) lib/postgrex/utils.ex:66: Postgrex.Utils.parse_version/1
    (postgrex) lib/postgrex/protocol.ex:663: Postgrex.Protocol.bootstrap_send/6
    (postgrex) lib/postgrex/protocol.ex:497: Postgrex.Protocol.handshake/2
    (db_connection) lib/db_connection/connection.ex:134: DBConnection.Connection.connect/2
Last message: nil
```

**Comment by josevalim** [comment]
So this is fixed in Postgrex. It is just Ecto using an old version, sorry.
