### ISSUE TITLE
error running migrations

### ISSUE THREAD

**Issue by happysalada** [elixir-ecto/postgrex#428]
I get an errror running my migrations. I'm running postgrex 14.0 with ecto 3.0

Here is the error I get
```
00:41:38.291 [error] an exception was raised logging %DBConnection.LogEntry{call: :prepare_execute, connection_time: 344317, decode_time: 8247259, params: [], pool_time: 71427753, query: %Postgrex.Query{cache: :reference, columns: nil, name: "", param_formats: nil, param_oids: nil, param_types: nil, ref: nil, result_formats: nil, result_oids: nil, result_types: nil, statement: ["CREATE TABLE ", "IF NOT EXISTS ", [34, "schema_migrations", 34], 32, 40, [[[], [[34, "version", 34], 32, "bigint", [[], []]], ", "], [34, "inserted_at", 34], 32, ["timestamp", "(0)"], [[], []]], [", ", "PRIMARY KEY (", [[], 34, "version", 34], ")"], 41, []], types: nil}, result: {:ok, %Postgrex.Query{cache: :reference, columns: nil, name: "", param_formats: [], param_oids: [], param_types: [], ref: #Reference<0.2077835036.3294363649.48140>, result_formats: [], result_oids: nil, result_types: nil, statement: ["CREATE TABLE ", "IF NOT EXISTS ", [34, "schema_migrations", 34], 32, 40, [[[], [[34, "version", 34], 32, "bigint", [[], []]], ", "], [34, "inserted_at", 34], 32, ["timestamp", "(0)"], [[], []]], [", ", "PRIMARY KEY (", [[], 34, "version", 34], ")"], 41, []], types: {Postgrex.DefaultTypes, #Reference<0.2077835036.3294494721.48090>}}, %Postgrex.Result{columns: nil, command: :create_table, connection_id: 7250, messages: [%{code: "42P07", file: "parse_utilcmd.c", line: "206", message: "relation \"schema_migrations\" already exists, skipping", routine: "transformCreateStmt", severity: "NOTICE", unknown: "NOTICE"}], num_rows: 0, rows: nil}}}: ** (ArgumentError) argument error
Nov 20 09:41:38 1362f30f9ec7 staging_web.1.de5bs80ltl8wxnayh9dh1hqq3:     (stdlib) :ets.lookup(Telemetry.HandlerTable, [:union, :repo, :query])
Nov 20 09:41:38 1362f30f9ec7 staging_web.1.de5bs80ltl8wxnayh9dh1hqq3:     (telemetry) lib/telemetry/handler_table.ex:59: Telemetry.HandlerTable.list_for_event/1
Nov 20 09:41:38 1362f30f9ec7 staging_web.1.de5bs80ltl8wxnayh9dh1hqq3:     (telemetry) lib/telemetry.ex:76: Telemetry.execute/3
Nov 20 09:41:38 1362f30f9ec7 staging_web.1.de5bs80ltl8wxnayh9dh1hqq3:     (ecto_sql) lib/ecto/adapters/sql.ex:754: Ecto.Adapters.SQL.log/4
Nov 20 09:41:38 1362f30f9ec7 staging_web.1.de5bs80ltl8wxnayh9dh1hqq3:     (db_connection) lib/db_connection.ex:1303: DBConnection.log/5
Nov 20 09:41:38 1362f30f9ec7 staging_web.1.de5bs80ltl8wxnayh9dh1hqq3:     (postgrex) lib/postgrex.ex:188: Postgrex.query_prepare_execute/4
Nov 20 09:41:38 1362f30f9ec7 staging_web.1.de5bs80ltl8wxnayh9dh1hqq3:     (ecto_sql) lib/ecto/adapters/sql.ex:288: Ecto.Adapters.SQL.query!/4
Nov 20 09:41:38 1362f30f9ec7 staging_web.1.de5bs80ltl8wxnayh9dh1hqq3:     (elixir) lib/enum.ex:1314: Enum."-map/2-lists^map/1-0-"/2
Nov 20 09:41:38 1362f30f9ec7 staging_web.1.de5bs80ltl8wxnayh9dh1hqq3: 00:41:38.329 [error] an exception was raised logging %DBConnection.LogEntry{call: :begin, connection_time: 251680, decode_time: nil, params: nil, pool_time: 36295, query: :begin, result: {:ok, %DBConnection{conn_mode: nil, conn_ref: #Reference<0.2077835036.3294363649.48247>, pool_ref: {:pool_ref, #PID<0.133.0>, #Reference<0.2077835036.3294494721.47914>, nil, #Reference<0.2077835036.3294494721.48135>, #Reference<0.2077835036.3294363649.48246>}}, %Postgrex.Result{columns: nil, command: :commit, connection_id: 7250, messages: [], num_rows: nil, rows: nil}}}: ** (ArgumentError) argument error
Nov 20 09:41:38 1362f30f9ec7 staging_web.1.de5bs80ltl8wxnayh9dh1hqq3:     (stdlib) :ets.lookup(Telemetry.HandlerTable, [:union, :repo, :query])
Nov 20 09:41:38 1362f30f9ec7 staging_web.1.de5bs80ltl8wxnayh9dh1hqq3:     (telemetry) lib/telemetry/handler_table.ex:59: Telemetry.HandlerTable.list_for_event/1
Nov 20 09:41:38 1362f30f9ec7 staging_web.1.de5bs80ltl8wxnayh9dh1hqq3:     (telemetry) lib/telemetry.ex:76: Telemetry.execute/3
Nov 20 09:41:38 1362f30f9ec7 staging_web.1.de5bs80ltl8wxnayh9dh1hqq3:     (ecto_sql) lib/ecto/adapters/sql.ex:754: Ecto.Adapters.SQL.log/4
Nov 20 09:41:38 1362f30f9ec7 staging_web.1.de5bs80ltl8wxnayh9dh1hqq3:     (db_connection) lib/db_connection.ex:1303: DBConnection.log/5
Nov 20 09:41:38 1362f30f9ec7 staging_web.1.de5bs80ltl8wxnayh9dh1hqq3:     (db_connection) lib/db_connection.ex:760: DBConnection.transaction/3
Nov 20 09:41:38 1362f30f9ec7 staging_web.1.de5bs80ltl8wxnayh9dh1hqq3:     (ecto_sql) lib/ecto/adapters/sql.ex:692: Ecto.Adapters.SQL.lock_for_migrations/4
Nov 20 09:41:38 1362f30f9ec7 staging_web.1.de5bs80ltl8wxnayh9dh1hqq3:     (ecto_sql) lib/ecto/migrator.ex:317: Ecto.Migrator.lock_for_migrations/3
Nov 20 09:41:38 1362f30f9ec7 staging_web.1.de5bs80ltl8wxnayh9dh1hqq3: 00:41:38.367 [error] an exception was raised logging %DBConnection.LogEntry{call: :prepare_execute, connection_time: 1215295, decode_time: 14453, params: [], pool_time: nil, query: %Postgrex.Query{cache: :reference, columns: nil, name: "ecto_50", param_formats: nil, param_oids: nil, param_types: nil, ref: nil, result_formats: nil, result_oids: nil, result_types: nil, statement: "SELECT s0.\"version\"::bigint FROM \"schema_migrations\" AS s0 FOR UPDATE", types: nil}, result: {:ok, %Postgrex.Query{cache: :reference, columns: ["version"], name: "ecto_50", param_formats: [], param_oids: [], param_types: [], ref: #Reference<0.2077835036.3294363649.48276>, result_formats: [:binary], result_oids: [20], result_types: [Postgrex.Extensions.Int8], statement: "SELECT s0.\"version\"::bigint FROM \"schema_migrations\" AS s0 FOR UPDATE", types: {Postgrex.DefaultTypes, #Reference<0.2077835036.3294494721.48090>}}, %Postgrex.Result{columns: ["version"], command: :select, connection_id: 7250, messages: [], num_rows: 94, rows: [[20170817002627], [20170817003845], [20170817045138], [20170901160212], [20170907160212], [20170908082120], [20170908085748], [20170917070541], [20170917082508], [20170922051950], [20170922192527], [20170923023516], [20170923165044], [20171002105454], [20171007031041], [20171008031041], [20171030105824], [20171212143912], [20180101092243], [20180103215359], [20180105134830], [20180106073049], [20180106103608], [20180106134459], [20180106154245], [20180110072641], [20180115162350], [20180118162023], [20180207012117], [20180211015839], [20180211042058], [20180211123318], [20180218022325], [...], ...]}}}: ** (ArgumentError) argument error
Nov 20 09:41:38 1362f30f9ec7 staging_web.1.de5bs80ltl8wxnayh9dh1hqq3:     (stdlib) :ets.lookup(Telemetry.HandlerTable, [:union, :repo, :query])
Nov 20 09:41:38 1362f30f9ec7 staging_web.1.de5bs80ltl8wxnayh9dh1hqq3:     (telemetry) lib/telemetry/handler_table.ex:59: Telemetry.HandlerTable.list_for_event/1
Nov 20 09:41:38 1362f30f9ec7 staging_web.1.de5bs80ltl8wxnayh9dh1hqq3:     (telemetry) lib/telemetry.ex:76: Telemetry.execute/3
Nov 20 09:41:38 1362f30f9ec7 staging_web.1.de5bs80ltl8wxnayh9dh1hqq3:     (ecto_sql) lib/ecto/adapters/sql.ex:754: Ecto.Adapters.SQL.log/4
Nov 20 09:41:38 1362f30f9ec7 staging_web.1.de5bs80ltl8wxnayh9dh1hqq3:     (db_connection) lib/db_connection.ex:1303: DBConnection.log/5
Nov 20 09:41:38 1362f30f9ec7 staging_web.1.de5bs80ltl8wxnayh9dh1hqq3:     (ecto_sql) lib/ecto/adapters/sql.ex:531: Ecto.Adapters.SQL.execute!/4
Nov 20 09:41:38 1362f30f9ec7 staging_web.1.de5bs80ltl8wxnayh9dh1hqq3:     (ecto_sql) lib/ecto/adapters/sql.ex:523: Ecto.Adapters.SQL.execute/5
Nov 20 09:41:38 1362f30f9ec7 staging_web.1.de5bs80ltl8wxnayh9dh1hqq3:     (ecto) lib/ecto/repo/queryable.ex:147: Ecto.Repo.Queryable.execute/4
Nov 20 09:41:38 1362f30f9ec7 staging_web.1.de5bs80ltl8wxnayh9dh1hqq3: 00:41:38.383 [info] Already up
Nov 20 09:41:38 1362f30f9ec7 staging_web.1.de5bs80ltl8wxnayh9dh1hqq3: Success!
Nov 20 09:41:38 1362f30f9ec7 staging_web.1.de5bs80ltl8wxnayh9dh1hqq3: 00:41:38.398 [error] an exception was raised logging %DBConnection.LogEntry{call: :commit, connection_time: 3696570, decode_time: nil, params: nil, pool_time: nil, query: :commit, result: {:ok, %Postgrex.Result{columns: nil, command: :commit, connection_id: 7250, messages: [], num_rows: nil, rows: nil}}}: ** (ArgumentError) argument error
Nov 20 09:41:38 1362f30f9ec7 staging_web.1.de5bs80ltl8wxnayh9dh1hqq3:     (stdlib) :ets.lookup(Telemetry.HandlerTable, [:union, :repo, :query])
Nov 20 09:41:38 1362f30f9ec7 staging_web.1.de5bs80ltl8wxnayh9dh1hqq3:     (telemetry) lib/telemetry/handler_table.ex:59: Telemetry.HandlerTable.list_for_event/1
Nov 20 09:41:38 1362f30f9ec7 staging_web.1.de5bs80ltl8wxnayh9dh1hqq3:     (telemetry) lib/telemetry.ex:76: Telemetry.execute/3
Nov 20 09:41:38 1362f30f9ec7 staging_web.1.de5bs80ltl8wxnayh9dh1hqq3:     (ecto_sql) lib/ecto/adapters/sql.ex:754: Ecto.Adapters.SQL.log/4
Nov 20 09:41:38 1362f30f9ec7 staging_web.1.de5bs80ltl8wxnayh9dh1hqq3:     (db_connection) lib/db_connection.ex:1303: DBConnection.log/5
Nov 20 09:41:38 1362f30f9ec7 staging_web.1.de5bs80ltl8wxnayh9dh1hqq3:     (db_connection) lib/db_connection.ex:1363: DBConnection.run_transaction/4
Nov 20 09:41:38 1362f30f9ec7 staging_web.1.de5bs80ltl8wxnayh9dh1hqq3:     (ecto_sql) lib/ecto/adapters/sql.ex:692: Ecto.Adapters.SQL.lock_for_migrations/4
Nov 20 09:41:38 1362f30f9ec7 staging_web.1.de5bs80ltl8wxnayh9dh1hqq3:     (ecto_sql) lib/ecto/migrator.ex:317: Ecto.Migrator.lock_for_migrations/3 
```

Here is my mix.lock
```
%{
  "absinthe": {:hex, :absinthe, "1.4.13", "81eb2ff41f1b62cd6e992955f62c22c042d1079b7936c27f5f7c2c806b8fc436", [:mix], [{:dataloader, "~> 1.0.0", [hex: :dataloader, repo: "hexpm", optional: true]}, {:decimal, "~> 1.0", [hex: :decimal, repo: "hexpm", optional: true]}], "hexpm"},
  "absinthe_plug": {:hex, :absinthe_plug, "1.4.6", "ac5d2d3d02acf52fda0f151b294017ab06e2ed1c6c15334e06aac82c94e36e08", [:mix], [{:absinthe, "~> 1.4.11", [hex: :absinthe, repo: "hexpm", optional: false]}, {:plug, "~> 1.3.2 or ~> 1.4", [hex: :plug, repo: "hexpm", optional: false]}], "hexpm"},
  "artificery": {:hex, :artificery, "0.2.6", "f602909757263f7897130cbd006b0e40514a541b148d366ad65b89236b93497a", [:mix], [], "hexpm"},
  "base64url": {:hex, :base64url, "0.0.1", "36a90125f5948e3afd7be97662a1504b934dd5dac78451ca6e9abf85a10286be", [:rebar], [], "hexpm"},
  "bcrypt_elixir": {:hex, :bcrypt_elixir, "1.1.1", "6b5560e47a02196ce5f0ab3f1d8265db79a23868c137e973b27afef928ed8006", [:make, :mix], [{:elixir_make, "~> 0.4", [hex: :elixir_make, repo: "hexpm", optional: false]}], "hexpm"},
  "bunt": {:hex, :bunt, "0.2.0", "951c6e801e8b1d2cbe58ebbd3e616a869061ddadcc4863d0a2182541acae9a38", [:mix], [], "hexpm"},
  "certifi": {:hex, :certifi, "2.4.2", "75424ff0f3baaccfd34b1214184b6ef616d89e420b258bb0a5ea7d7bc628f7f0", [:rebar3], [{:parse_trans, "~>3.3", [hex: :parse_trans, repo: "hexpm", optional: false]}], "hexpm"},
  "cloudex": {:hex, :cloudex, "1.2.1", "fd2b115c8519399f11c63d11c13ff98a88d381196c01228a206e0af12dee13dd", [:mix], [{:httpoison, "~> 1.3.0", [hex: :httpoison, repo: "hexpm", optional: false]}, {:poison, "~> 3.1.0", [hex: :poison, repo: "hexpm", optional: false]}, {:timex, "~> 3.4.2", [hex: :timex, repo: "hexpm", optional: false]}, {:tzdata, "~> 0.5.11", [hex: :tzdata, repo: "hexpm", optional: false]}], "hexpm"},
  "combine": {:hex, :combine, "0.10.0", "eff8224eeb56498a2af13011d142c5e7997a80c8f5b97c499f84c841032e429f", [:mix], [], "hexpm"},
  "comeonin": {:hex, :comeonin, "4.1.1", "c7304fc29b45b897b34142a91122bc72757bc0c295e9e824999d5179ffc08416", [:mix], [{:argon2_elixir, "~> 1.2", [hex: :argon2_elixir, repo: "hexpm", optional: true]}, {:bcrypt_elixir, "~> 0.12.1 or ~> 1.0", [hex: :bcrypt_elixir, repo: "hexpm", optional: true]}, {:pbkdf2_elixir, "~> 0.12", [hex: :pbkdf2_elixir, repo: "hexpm", optional: true]}], "hexpm"},
  "connection": {:hex, :connection, "1.0.4", "a1cae72211f0eef17705aaededacac3eb30e6625b04a6117c1b2db6ace7d5976", [:mix], [], "hexpm"},
  "cowboy": {:hex, :cowboy, "2.6.0", "dc1ff5354c89e36a3e3ef8d10433396dcff0dcbb1d4223b58c64c2d51a6d88d9", [:rebar3], [{:cowlib, "~> 2.7.0", [hex: :cowlib, repo: "hexpm", optional: false]}, {:ranch, "~> 1.7.0", [hex: :ranch, repo: "hexpm", optional: false]}], "hexpm"},
  "cowlib": {:hex, :cowlib, "2.7.0", "3ef16e77562f9855a2605900cedb15c1462d76fb1be6a32fc3ae91973ee543d2", [:rebar3], [], "hexpm"},
  "credo": {:hex, :credo, "1.0.0", "aaa40fdd0543a0cf8080e8c5949d8c25f0a24e4fc8c1d83d06c388f5e5e0ea42", [:mix], [{:bunt, "~> 0.2.0", [hex: :bunt, repo: "hexpm", optional: false]}, {:jason, "~> 1.0", [hex: :jason, repo: "hexpm", optional: false]}], "hexpm"},
  "db_connection": {:hex, :db_connection, "2.0.2", "440c05518b0bdca0469dafaf45403597430448c1281def14ef9ccaa41833ea1e", [:mix], [{:connection, "~> 1.0.2", [hex: :connection, repo: "hexpm", optional: false]}], "hexpm"},
  "decimal": {:hex, :decimal, "1.5.0", "b0433a36d0e2430e3d50291b1c65f53c37d56f83665b43d79963684865beab68", [:mix], [], "hexpm"},
  "dialyxir": {:hex, :dialyxir, "0.5.1", "b331b091720fd93e878137add264bac4f644e1ddae07a70bf7062c7862c4b952", [:mix], [], "hexpm"},
  "distillery": {:hex, :distillery, "2.0.12", "6e78fe042df82610ac3fa50bd7d2d8190ad287d120d3cd1682d83a44e8b34dfb", [:mix], [{:artificery, "~> 0.2", [hex: :artificery, repo: "hexpm", optional: false]}], "hexpm"},
  "earmark": {:hex, :earmark, "1.2.6", "b6da42b3831458d3ecc57314dff3051b080b9b2be88c2e5aa41cd642a5b044ed", [:mix], [], "hexpm"},
  "ecto": {:hex, :ecto, "3.0.2", "9d06ece60e2fc9b7593e74ede23747424ef32390016baca85cea3f4b84081c52", [:mix], [{:decimal, "~> 1.5", [hex: :decimal, repo: "hexpm", optional: false]}, {:jason, "~> 1.0", [hex: :jason, repo: "hexpm", optional: true]}, {:poison, "~> 2.2 or ~> 3.0", [hex: :poison, repo: "hexpm", optional: true]}], "hexpm"},
  "ecto_enum": {:hex, :ecto_enum, "1.1.0", "d44fe2ce6e1c0e907e7c3b6456a69e0f1d662348d8b4e2a662ba312223d8ff62", [:mix], [{:ecto, ">= 2.0.0", [hex: :ecto, repo: "hexpm", optional: false]}, {:mariaex, ">= 0.0.0", [hex: :mariaex, repo: "hexpm", optional: true]}, {:postgrex, ">= 0.0.0", [hex: :postgrex, repo: "hexpm", optional: true]}], "hexpm"},
  "ecto_sql": {:hex, :ecto_sql, "3.0.1", "7f0e123a3b4d3b8ac67da6ba3014c53dbed63e614c5086f3e99d01cab5defe27", [:mix], [{:db_connection, "~> 2.0", [hex: :db_connection, repo: "hexpm", optional: false]}, {:ecto, "~> 3.0.2", [hex: :ecto, repo: "hexpm", optional: false]}, {:mariaex, "~> 0.9.1", [hex: :mariaex, repo: "hexpm", optional: true]}, {:postgrex, "~> 0.14.0", [hex: :postgrex, repo: "hexpm", optional: true]}, {:telemetry, "~> 0.2.0", [hex: :telemetry, repo: "hexpm", optional: false]}], "hexpm"},
  "eflame": {:hex, :eflame, "1.0.1", "0664d287e39eef3c413749254b3af5f4f8b00be71c1af67d325331c4890be0fc", [:mix], [], "hexpm"},
  "elixir_make": {:hex, :elixir_make, "0.4.2", "332c649d08c18bc1ecc73b1befc68c647136de4f340b548844efc796405743bf", [:mix], [], "hexpm"},
  "ex_doc": {:hex, :ex_doc, "0.19.1", "519bb9c19526ca51d326c060cb1778d4a9056b190086a8c6c115828eaccea6cf", [:mix], [{:earmark, "~> 1.1", [hex: :earmark, repo: "hexpm", optional: false]}, {:makeup_elixir, "~> 0.7", [hex: :makeup_elixir, repo: "hexpm", optional: false]}], "hexpm"},
  "excoveralls": {:hex, :excoveralls, "0.10.3", "b090a3fbcb3cfa136f0427d038c92a9051f840953ec11b40ee74d9d4eac04d1e", [:mix], [{:hackney, "~> 1.13", [hex: :hackney, repo: "hexpm", optional: false]}, {:jason, "~> 1.0", [hex: :jason, repo: "hexpm", optional: false]}], "hexpm"},
  "exprintf": {:hex, :exprintf, "0.2.1", "b7e895dfb00520cfb7fc1671303b63b37dc3897c59be7cbf1ae62f766a8a0314", [:mix], [], "hexpm"},
  "exprof": {:hex, :exprof, "0.2.3", "8d4d657d73fc0c9ef1e30b2f9207b26ccbd2aec2baf1ca43f0b6d244c841c9f8", [:mix], [{:exprintf, "~> 0.2", [hex: :exprintf, repo: "hexpm", optional: false]}], "hexpm"},
  "file_system": {:hex, :file_system, "0.2.6", "fd4dc3af89b9ab1dc8ccbcc214a0e60c41f34be251d9307920748a14bf41f1d3", [:mix], [], "hexpm"},
  "gettext": {:hex, :gettext, "0.16.1", "e2130b25eebcbe02bb343b119a07ae2c7e28bd4b146c4a154da2ffb2b3507af2", [:mix], [], "hexpm"},
  "guardian": {:hex, :guardian, "1.1.1", "be14c4007eaf05268251ae114030cb7237ed9a9631c260022f020164ff4ed733", [:mix], [{:jose, "~> 1.8", [hex: :jose, repo: "hexpm", optional: false]}, {:phoenix, "~> 1.0 or ~> 1.2 or ~> 1.3", [hex: :phoenix, repo: "hexpm", optional: true]}, {:plug, "~> 1.3.3 or ~> 1.4", [hex: :plug, repo: "hexpm", optional: true]}, {:poison, "~> 2.2 or ~> 3.0", [hex: :poison, repo: "hexpm", optional: false]}], "hexpm"},
  "hackney": {:hex, :hackney, "1.14.3", "b5f6f5dcc4f1fba340762738759209e21914516df6be440d85772542d4a5e412", [:rebar3], [{:certifi, "2.4.2", [hex: :certifi, repo: "hexpm", optional: false]}, {:idna, "6.0.0", [hex: :idna, repo: "hexpm", optional: false]}, {:metrics, "1.0.1", [hex: :metrics, repo: "hexpm", optional: false]}, {:mimerl, "1.0.2", [hex: :mimerl, repo: "hexpm", optional: false]}, {:ssl_verify_fun, "1.1.4", [hex: :ssl_verify_fun, repo: "hexpm", optional: false]}], "hexpm"},
  "httpoison": {:hex, :httpoison, "1.3.1", "7ac607311f5f706b44e8b3fab736d0737f2f62a31910ccd9afe7227b43edb7f0", [:mix], [{:hackney, "~> 1.8", [hex: :hackney, repo: "hexpm", optional: false]}], "hexpm"},
  "idna": {:hex, :idna, "6.0.0", "689c46cbcdf3524c44d5f3dde8001f364cd7608a99556d8fbd8239a5798d4c10", [:rebar3], [{:unicode_util_compat, "0.4.1", [hex: :unicode_util_compat, repo: "hexpm", optional: false]}], "hexpm"},
  "jason": {:hex, :jason, "1.1.2", "b03dedea67a99223a2eaf9f1264ce37154564de899fd3d8b9a21b1a6fd64afe7", [:mix], [{:decimal, "~> 1.0", [hex: :decimal, repo: "hexpm", optional: true]}], "hexpm"},
  "jose": {:hex, :jose, "1.8.4", "7946d1e5c03a76ac9ef42a6e6a20001d35987afd68c2107bcd8f01a84e75aa73", [:mix, :rebar3], [{:base64url, "~> 0.0.1", [hex: :base64url, repo: "hexpm", optional: false]}], "hexpm"},
  "makeup": {:hex, :makeup, "0.5.5", "9e08dfc45280c5684d771ad58159f718a7b5788596099bdfb0284597d368a882", [:mix], [{:nimble_parsec, "~> 0.4", [hex: :nimble_parsec, repo: "hexpm", optional: false]}], "hexpm"},
  "makeup_elixir": {:hex, :makeup_elixir, "0.10.0", "0f09c2ddf352887a956d84f8f7e702111122ca32fbbc84c2f0569b8b65cbf7fa", [:mix], [{:makeup, "~> 0.5.5", [hex: :makeup, repo: "hexpm", optional: false]}], "hexpm"},
  "metrics": {:hex, :metrics, "1.0.1", "25f094dea2cda98213cecc3aeff09e940299d950904393b2a29d191c346a8486", [:rebar3], [], "hexpm"},
  "mime": {:hex, :mime, "1.3.0", "5e8d45a39e95c650900d03f897fbf99ae04f60ab1daa4a34c7a20a5151b7a5fe", [:mix], [], "hexpm"},
  "mimerl": {:hex, :mimerl, "1.0.2", "993f9b0e084083405ed8252b99460c4f0563e41729ab42d9074fd5e52439be88", [:rebar3], [], "hexpm"},
  "nimble_parsec": {:hex, :nimble_parsec, "0.4.0", "ee261bb53214943679422be70f1658fff573c5d0b0a1ecd0f18738944f818efe", [:mix], [], "hexpm"},
  "number": {:hex, :number, "0.5.7", "da1ee0434f3c7b84360d33b335d0ee2f86f247f45fbe2e7636e6f55680b464dd", [:mix], [{:decimal, "~> 1.2", [hex: :decimal, repo: "hexpm", optional: false]}], "hexpm"},
  "observer_cli": {:hex, :observer_cli, "1.4.1", "8c829bb28e3f316a361216314405fe296d8dd2fd7409dfa53fa4ac1cff3797a0", [:rebar3], [{:recon, "2.3.6", [hex: :recon, repo: "hexpm", optional: false]}], "hexpm"},
  "parent": {:hex, :parent, "0.5.1", "fed79e79402a1f91bffb117e0ef01fd802345dde79fb70df317f8857f2679237", [:mix], [], "hexpm"},
  "parse_trans": {:hex, :parse_trans, "3.3.0", "09765507a3c7590a784615cfd421d101aec25098d50b89d7aa1d66646bc571c1", [:rebar3], [], "hexpm"},
  "phoenix": {:hex, :phoenix, "1.4.0", "56fe9a809e0e735f3e3b9b31c1b749d4b436e466d8da627b8d82f90eaae714d2", [:mix], [{:jason, "~> 1.0", [hex: :jason, repo: "hexpm", optional: true]}, {:phoenix_pubsub, "~> 1.1", [hex: :phoenix_pubsub, repo: "hexpm", optional: false]}, {:plug, "~> 1.7", [hex: :plug, repo: "hexpm", optional: false]}, {:plug_cowboy, "~> 1.0 or ~> 2.0", [hex: :plug_cowboy, repo: "hexpm", optional: true]}], "hexpm"},
  "phoenix_ecto": {:hex, :phoenix_ecto, "4.0.0", "c43117a136e7399ea04ecaac73f8f23ee0ffe3e07acfcb8062fe5f4c9f0f6531", [:mix], [{:ecto, "~> 3.0", [hex: :ecto, repo: "hexpm", optional: false]}, {:phoenix_html, "~> 2.9", [hex: :phoenix_html, repo: "hexpm", optional: true]}, {:plug, "~> 1.0", [hex: :plug, repo: "hexpm", optional: false]}], "hexpm"},
  "phoenix_html": {:hex, :phoenix_html, "2.12.0", "1fb3c2e48b4b66d75564d8d63df6d53655469216d6b553e7e14ced2b46f97622", [:mix], [{:plug, "~> 1.5", [hex: :plug, repo: "hexpm", optional: false]}], "hexpm"},
  "phoenix_live_reload": {:hex, :phoenix_live_reload, "1.2.0", "3bb31a9fbd40ffe8652e60c8660dffd72dd231efcdf49b744fb75b9ef7db5dd2", [:mix], [{:file_system, "~> 0.2.1 or ~> 0.3", [hex: :file_system, repo: "hexpm", optional: false]}, {:phoenix, "~> 1.4", [hex: :phoenix, repo: "hexpm", optional: false]}], "hexpm"},
  "phoenix_pubsub": {:hex, :phoenix_pubsub, "1.1.1", "6668d787e602981f24f17a5fbb69cc98f8ab085114ebfac6cc36e10a90c8e93c", [:mix], [], "hexpm"},
  "plug": {:hex, :plug, "1.7.1", "8516d565fb84a6a8b2ca722e74e2cd25ca0fc9d64f364ec9dbec09d33eb78ccd", [:mix], [{:mime, "~> 1.0", [hex: :mime, repo: "hexpm", optional: false]}, {:plug_crypto, "~> 1.0", [hex: :plug_crypto, repo: "hexpm", optional: false]}], "hexpm"},
  "plug_cowboy": {:hex, :plug_cowboy, "2.0.0", "ab0c92728f2ba43c544cce85f0f220d8d30fc0c90eaa1e6203683ab039655062", [:mix], [{:cowboy, "~> 2.5", [hex: :cowboy, repo: "hexpm", optional: false]}, {:plug, "~> 1.7", [hex: :plug, repo: "hexpm", optional: false]}], "hexpm"},
  "plug_crypto": {:hex, :plug_crypto, "1.0.0", "18e49317d3fa343f24620ed22795ec29d4a5e602d52d1513ccea0b07d8ea7d4d", [:mix], [], "hexpm"},
  "poison": {:hex, :poison, "3.1.0", "d9eb636610e096f86f25d9a46f35a9facac35609a7591b3be3326e99a0484665", [:mix], [], "hexpm"},
  "postgrex": {:hex, :postgrex, "0.14.0", "f3d6ffea1ca8a156e0633900a5338a3d17b00435227726baed8982718232b694", [:mix], [{:connection, "~> 1.0", [hex: :connection, repo: "hexpm", optional: false]}, {:db_connection, "~> 2.0", [hex: :db_connection, repo: "hexpm", optional: false]}, {:decimal, "~> 1.0", [hex: :decimal, repo: "hexpm", optional: false]}, {:jason, "~> 1.0", [hex: :jason, repo: "hexpm", optional: true]}], "hexpm"},
  "ranch": {:hex, :ranch, "1.7.0", "9583f47160ca62af7f8d5db11454068eaa32b56eeadf984d4f46e61a076df5f2", [:rebar3], [], "hexpm"},
  "recon": {:hex, :recon, "2.3.6", "2bcad0cf621fb277cabbb6413159cd3aa30265c2dee42c968697988b30108604", [:rebar3], [], "hexpm"},
  "sentry": {:hex, :sentry, "7.0.3", "093fa4b6937760afb9a5fcb0e4a9092a305b6c0ff26a710e977614b201feab75", [:mix], [{:hackney, "~> 1.8 or 1.6.5", [hex: :hackney, repo: "hexpm", optional: false]}, {:jason, "~> 1.1", [hex: :jason, repo: "hexpm", optional: true]}, {:phoenix, "~> 1.3", [hex: :phoenix, repo: "hexpm", optional: true]}, {:plug, "~> 1.6", [hex: :plug, repo: "hexpm", optional: true]}, {:plug_cowboy, "~> 1.0 or ~> 2.0", [hex: :plug_cowboy, repo: "hexpm", optional: true]}], "hexpm"},
  "site_encrypt": {:git, "https://github.com/sasa1977/site_encrypt.git", "c76576b8948b77d74cb1808b5eedc75c983a545c", []},
  "ssl_verify_fun": {:hex, :ssl_verify_fun, "1.1.4", "f0eafff810d2041e93f915ef59899c923f4568f4585904d010387ed74988e77b", [:make, :mix, :rebar3], [], "hexpm"},
  "swoosh": {:hex, :swoosh, "0.20.0", "9a6c13822c9815993c03b6f8fccc370fcffb3c158d9754f67b1fdee6b3a5d928", [:mix], [{:cowboy, "~> 1.0.1 or ~> 1.1 or ~> 2.4", [hex: :cowboy, repo: "hexpm", optional: true]}, {:gen_smtp, "~> 0.12", [hex: :gen_smtp, repo: "hexpm", optional: true]}, {:hackney, "~> 1.9", [hex: :hackney, repo: "hexpm", optional: false]}, {:jason, "~> 1.0", [hex: :jason, repo: "hexpm", optional: false]}, {:mime, "~> 1.1", [hex: :mime, repo: "hexpm", optional: false]}, {:plug, "~> 1.4", [hex: :plug, repo: "hexpm", optional: true]}], "hexpm"},
  "telemetry": {:hex, :telemetry, "0.2.0", "5b40caa3efe4deb30fb12d7cd8ed4f556f6d6bd15c374c2366772161311ce377", [:mix], [], "hexpm"},
  "timex": {:hex, :timex, "3.4.2", "d74649c93ad0e12ce5b17cf5e11fbd1fb1b24a3d114643e86dba194b64439547", [:mix], [{:combine, "~> 0.10", [hex: :combine, repo: "hexpm", optional: false]}, {:gettext, "~> 0.10", [hex: :gettext, repo: "hexpm", optional: false]}, {:tzdata, "~> 0.1.8 or ~> 0.5", [hex: :tzdata, repo: "hexpm", optional: false]}], "hexpm"},
  "turbolinks": {:hex, :turbolinks, "1.0.1", "ee48ddc70884c738ff5a58a004d2565276cf5841f3ef43c22afd884d0404603e", [:mix], [{:phoenix, "~> 1.0", [hex: :phoenix, repo: "hexpm", optional: false]}, {:plug, "~> 1.0", [hex: :plug, repo: "hexpm", optional: false]}], "hexpm"},
  "tzdata": {:hex, :tzdata, "0.5.19", "7962a3997bf06303b7d1772988ede22260f3dae1bf897408ebdac2b4435f4e6a", [:mix], [{:hackney, "~> 1.0", [hex: :hackney, repo: "hexpm", optional: false]}], "hexpm"},
  "unicode_util_compat": {:hex, :unicode_util_compat, "0.4.1", "d869e4c68901dd9531385bb0c8c40444ebf624e60b6962d95952775cac5e90cd", [:rebar3], [], "hexpm"},
  "x509": {:hex, :x509, "0.3.0", "c6f3db66960c6e4f424d1e6cca5c7d730e0a577af8dc115a613f4560ce1df6d3", [:mix], [], "hexpm"},
}
```
let me know if you need anything more. I you have ideas on where to search.
I am using postgres 11.1, that might be the cause of the error

**Comment by fishcakez** [comment]
Is https://github.com/elixir-ecto/ecto/issues/2793 the issue?
