### ISSUE TITLE
Postgrex.start_link crashes with KeyError

### ISSUE THREAD

**Issue by hectorsq** [elixir-ecto/postgrex#435]
I cloned an umbrella project that is working perfectly in my computer (macOS) to a colleague’s computer (macOS) and we are having problems with mix ecto.create.

Trying to isolate the problem we ran the following command in iex -S mix and we get the following error:

```
{:ok, pid} = Postgrex.start_link(hostname: "localhost", username: "postgres", password: "postgres", database: "postgres")
{:ok, #PID<0.397.0>}

15:06:05.107 [error] GenServer #PID<0.399.0> terminating
** (KeyError) key :messages not found in: %{opts: [types: Postgrex.DefaultTypes, hostname: "localhost", username: "postgres", password: "postgres", database: "postgres"], prepare: :named, ssl: false, types_key: {'localhost', 5432, "postgres"}, types_lock: {#PID<0.401.0>, #Reference<0.4115175174.1123287042.227985>}, types_mod: Postgrex.DefaultTypes}
    (stdlib) :maps.get(:messages, %{opts: [types: Postgrex.DefaultTypes, hostname: "localhost", username: "postgres", password: "postgres", database: "postgres"], prepare: :named, ssl: false, types_key: {'localhost', 5432, "postgres"}, types_lock: {#PID<0.401.0>, #Reference<0.4115175174.1123287042.227985>}, types_mod: Postgrex.DefaultTypes})
    (elixir) lib/map.ex:267: Map.update!/3
    (postgrex) lib/postgrex/protocol.ex:2815: Postgrex.Protocol.handle_msg/3
    (postgrex) lib/postgrex/protocol.ex:825: Postgrex.Protocol.bootstrap_recv/5
    (postgrex) lib/postgrex/protocol.ex:576: Postgrex.Protocol.handshake/2
    (db_connection) lib/db_connection/connection.ex:66: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol
```

We created an standalone phoenix project and worked fine. Seems that the problem is with the umbrella.

**Comment by josevalim** [comment]
Thanks @hectorsq!

It is weird that it worked on a regular project. Plus I just tried this in an umbrella app too and it worked here too. Hrm... could you please provide a minimal app that reproduces the issue then?

**Comment by wojtekmach** [comment]
Besides trying to have a minimal repro, could you also mention Elixir, Postgrex, and PG versions you're using?

This is a long shot: inside an umbrella, do you see a difference when you do: `rm -rf _build && iex -S mix` and `rm -rf  _build && cd apps/myapp && iex -S mix`?

**Comment by hectorsq** [comment]
José, Wojtek

I created a minimal repo at https://github.com/hectorsq/mx-test. It works on my computer. It does not work on my colleague’s computer.

The following tests were ran on my colleague's computer.

```
$ mix test

17:32:53.408 [error] GenServer #PID<0.2678.0> terminating
** (RuntimeError) connect raised KeyError exception: key :messages not found.The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true if you wish to see all of the details
    (stdlib) :maps.get/2
    (elixir) lib/map.ex:267: Map.update!/3
    (postgrex) lib/postgrex/protocol.ex:2815: Postgrex.Protocol.handle_msg/3
    (postgrex) lib/postgrex/protocol.ex:825: Postgrex.Protocol.bootstrap_recv/5
    (postgrex) lib/postgrex/protocol.ex:576: Postgrex.Protocol.handshake/2
    (db_connection) lib/db_connection/connection.ex:66: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol
** (Mix) The database for MxEcto.Repo couldn't be created: killed
```

``` 
 $ iex -S mix

17:41:45.584 [error] Postgrex.Protocol (#PID<0.2783.0>) failed to connect: ** (Postgrex.Error) FATAL 3D000 (invalid_catalog_name) database "mx_ecto_dev" does not exist
```
```
$ mix ecto.create

17:46:17.612 [error] GenServer #PID<0.241.0> terminating
** (RuntimeError) connect raised KeyError exception: key :messages not found.The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true if you wish to see all of the details
    (stdlib) :maps.get/2
    (elixir) lib/map.ex:267: Map.update!/3
    (postgrex) lib/postgrex/protocol.ex:2815: Postgrex.Protocol.handle_msg/3
    (postgrex) lib/postgrex/protocol.ex:825: Postgrex.Protocol.bootstrap_recv/5
    (postgrex) lib/postgrex/protocol.ex:576: Postgrex.Protocol.handshake/2
    (db_connection) lib/db_connection/connection.ex:66: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol
** (Mix) The database for MxEcto.Repo couldn't be created: killed
```
```
$ rm -rf _build && iex -S mix
17:52:19.992 [error] Postgrex.Protocol (#PID<0.2786.0>) failed to connect: ** (Postgrex.Error) FATAL 3D000 (invalid_catalog_name) database "mx_ecto_dev" does not exist

17:52:19.992 [error] Postgrex.Protocol (#PID<0.2789.0>) failed to connect: ** (Postgrex.Error) FATAL 3D000 (invalid_catalog_name) database "mx_ecto_dev" does not exist

17:52:19.992 [error] Postgrex.Protocol (#PID<0.2788.0>) failed to connect: ** (Postgrex.Error) FATAL 3D000 (invalid_catalog_name) database "mx_ecto_dev" does not exist

17:52:19.992 [error] Postgrex.Protocol (#PID<0.2791.0>) failed to connect: ** (Postgrex.Error) FATAL 3D000 (invalid_catalog_name) database "mx_ecto_dev" does not exist
.
.
.
```
```
$ rm -rf _build && cd apps/mx_web && iex -S mix
Interactive Elixir (1.8.0) - press Ctrl+C to exit (type h() ENTER for help)
```
```
$ rm -rf _build && cd apps/mx_ecto && iex -S mix
18:05:09.666 [error] Postgrex.Protocol (#PID<0.1352.0>) failed to connect: ** (Postgrex.Error) FATAL 3D000 (invalid_catalog_name) database "mx_ecto_dev" does not exist
```
```
psql
psql (10.5, server 9.5.14)
Type "help" for help.

Sulfur=# SHOW server_version;
LOG:  statement: SHOW server_version;
 server_version
----------------
 9.5.14
(1 row)
``` 
```
elixir -v
Erlang/OTP 21 [erts-10.2.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Elixir 1.8.0 (compiled with Erlang/OTP 20)
```
```
$ asdf current
elixir         1.8.0    (set by /Users/Sulfur/Documents/projects/mx-test/.tool-versions)
erlang         21.2.3   (set by /Users/Sulfur/Documents/projects/mx-test/.tool-versions)
```
This is going to be hard because it works on my computer perfectly but not in my colleague's computer.

Please let me know if we can make more tests.
