### ISSUE TITLE
Is Trust Authentication supported by postgrex and if yes, how can we use it?

### ISSUE THREAD

**Issue by jpbecotte** [elixir-ecto/postgrex#494]
From Postgres Doc: https://www.postgresql.org/docs/11/auth-trust.html, one can connect without specifying no password, no username, and no hostname.

This is a Postgres SQL server feature, not a psql feature.

Using the command line, if one can do `psql postgres:///db`, then running an elixir app under the same user should work.

**Comment by wojtekmach** [comment]
Yes, it's supported.

I have the following relevant part of `pg_hba.conf` (default for homebrew Postgres):

```
# TYPE  DATABASE        USER            ADDRESS                 METHOD

# "local" is for Unix domain socket connections only
local   all             all                                     trust
# IPv4 local connections:
host    all             all             127.0.0.1/32            trust
# IPv6 local connections:
host    all             all             ::1/128                 trust
# Allow replication connections from localhost, by a user with the
# replication privilege.
local   replication     all                                     trust
host    replication     all             127.0.0.1/32            trust
host    replication     all             ::1/128                 trust
```

and I can connect like this:

```
iex> {:ok, pid} = Postgrex.start_link(database: "wojtek")
```

**Comment by jpbecotte** [comment]
I have updated my pg_hba.conf. Here's what I got from `iex -S mix` on a new empty project where set Postgrex as a dependency:

```
app@vps267433:/apps/testconn$ iex -S mix
Erlang/OTP 22 [erts-10.6.2] [source] [64-bit] [smp:1:1] [ds:1:1:10] [async-threads:1]

Interactive Elixir (1.10.0-rc.0) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Postgrex.start_link(database: "db")
{:ok, #PID<0.209.0>}
iex(2)>
14:16:32.701 [error] GenServer #PID<0.211.0> terminating
** (RuntimeError) connect raised KeyError exception: key :password not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details
    (elixir 1.10.0-rc.0) lib/keyword.ex:399: Keyword.fetch!/2
    (postgrex 0.15.3) lib/postgrex/protocol.ex:722: Postgrex.Protocol.auth_md5/4
    (postgrex 0.15.3) lib/postgrex/protocol.ex:579: Postgrex.Protocol.handshake/2
    (db_connection 2.2.0) lib/db_connection/connection.ex:69: DBConnection.Connection.connect/2
    (connection 1.0.4) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib 3.11.1) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol

14:16:32.712 [error] GenServer #PID<0.216.0> terminating
** (RuntimeError) connect raised KeyError exception: key :password not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details
    (elixir 1.10.0-rc.0) lib/keyword.ex:399: Keyword.fetch!/2
    (postgrex 0.15.3) lib/postgrex/protocol.ex:722: Postgrex.Protocol.auth_md5/4
    (postgrex 0.15.3) lib/postgrex/protocol.ex:579: Postgrex.Protocol.handshake/2
    (db_connection 2.2.0) lib/db_connection/connection.ex:69: DBConnection.Connection.connect/2
    (connection 1.0.4) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib 3.11.1) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol

14:16:32.718 [error] GenServer #PID<0.217.0> terminating
** (RuntimeError) connect raised KeyError exception: key :password not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details
    (elixir 1.10.0-rc.0) lib/keyword.ex:399: Keyword.fetch!/2
    (postgrex 0.15.3) lib/postgrex/protocol.ex:722: Postgrex.Protocol.auth_md5/4
    (postgrex 0.15.3) lib/postgrex/protocol.ex:579: Postgrex.Protocol.handshake/2
    (db_connection 2.2.0) lib/db_connection/connection.ex:69: DBConnection.Connection.connect/2
    (connection 1.0.4) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib 3.11.1) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol

14:16:32.724 [error] GenServer #PID<0.218.0> terminating
** (RuntimeError) connect raised KeyError exception: key :password not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details
    (elixir 1.10.0-rc.0) lib/keyword.ex:399: Keyword.fetch!/2
    (postgrex 0.15.3) lib/postgrex/protocol.ex:722: Postgrex.Protocol.auth_md5/4
    (postgrex 0.15.3) lib/postgrex/protocol.ex:579: Postgrex.Protocol.handshake/2
    (db_connection 2.2.0) lib/db_connection/connection.ex:69: DBConnection.Connection.connect/2
    (connection 1.0.4) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib 3.11.1) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol
** (EXIT from #PID<0.207.0>) shell process exited with reason: killed

Interactive Elixir (1.10.0-rc.0) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)>

```

**Comment by jpbecotte** [comment]
Sorry it works now. I had to put all the entries of the file! Thank you for your help, it's pretty much appreciated!
