### ISSUE TITLE
Cannot connect to server with `client_min_messages` >= `debug[1-5]` 

### ISSUE THREAD

**Issue by richardkmichael** [elixir-ecto/postgrex#498]
PostgreSQL 12.2
Postgrex 0.15.3

(Similar to #451 ?)

Cannot connect to a 12.2 server when it has config: `client_min_messages = debug1`, and `debug{2,3,4,5}`

I have added whitespace to the backtrace to make is easier to see the four parameters to `msg_recv()`.

```elixir
iex(2)> {:ok, pid} = Postgrex.start_link(hostname: "localhost", username: "postgres", password: "postgres", database: "test", show_sensitive_data_on_connection_error: true)
{:ok, #PID<0.2853.0>}
iex(3)> [error] GenServer #PID<0.2855.0> terminating

** (FunctionClauseError) no function clause matching in Postgrex.Protocol.msg_recv/4

    (postgrex 0.15.3) lib/postgrex/protocol.ex:2836: Postgrex.Protocol.msg_recv(
  {
    {%Postgrex.Protocol{buffer: nil, connection_id: 37704, connection_key: -1269269119, disconnect_on_error_codes: [], null: nil, parameters: %
    {"DateStyle" => "ISO, MDY", "IntervalStyle" => "postgres", "TimeZone" => "America/Toronto", "application_name" => "", "client_encoding" => "UTF8", "integer_datetimes" => "on", "is_superuser" => "on", "server_encoding" =>
     "UTF8", "server_version" => "12.2", "session_authorization" => "postgres", "standard_conforming_strings" => "on"}, peer: {{127, 0, 0, 1}, 5432}, postgres: :idle, queries: nil, sock: {:gen_tcp, #Port<0.1231>}, timeout: 1
    5000, transactions: :naive, types: {Postgrex.DefaultTypes, #Reference<0.3052583275.3171549186.195678>}}, %{messages: [%{code: "00000", file: "catcache.c", line: "867", message: "rehashing catalog cache id 43 for pg_proc;
     257 tups, 128 buckets", routine: "RehashCatCache", severity: "DEBUG", unknown: "DEBUG"}], opts: [pool_index: 1, types: Postgrex.DefaultTypes, hostname: "localhost", username: "postgres", password: "postgres", database:
    "test", show_sensitive_data_on_connection_error: true], prepare: :named, ssl: false, types_key: {'localhost', 5432, "test"}, types_lock: {#PID<0.2799.0>, #Reference<0.3052583275.3171418117.194991>}, types_mod:
    Postgrex.DefaultTypes}},

    %{messages: [%{code: "00000", file: "catcache.c", line: "867", message: "rehashing catalog cache id 42 for pg_proc; 257 tups, 128 buckets", routine: "RehashCatCache", severity: "DEBUG", unknown:
    "DEBUG"}], opts: [pool_index: 1, types: Postgrex.DefaultTypes, hostname: "localhost", username: "postgres", password: "postgres", database: "test", show_sensitive_data_on_connection_error: true], prepare: :named, ss
    l: false, types_key: {'localhost', 5432, "test"}, types_lock: {#PID<0.2799.0>, #Reference<0.3052583275.3171418117.194991>}, types_mod: Postgrex.DefaultTypes}
  },
  :infinity,
  "",
  0)

    (postgrex 0.15.3) lib/postgrex/protocol.ex:816: Postgrex.Protocol.bootstrap_recv/4
    (postgrex 0.15.3) lib/postgrex/protocol.ex:579: Postgrex.Protocol.handshake/2
    (db_connection 2.2.1) lib/db_connection/connection.ex:69: DBConnection.Connection.connect/2
    (connection 1.0.4) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib 3.11.2) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol
```
```

**Comment by chvanikoff** [comment]
Just faced the same issue, but also want to add that for me it only fails when `log_statement=all` is set. Postgres version is 9.6.16

**Comment by josevalim** [comment]
PRs are welcome!
