### ISSUE TITLE
invalid Unix time 9224318721654775807 when running TimescaleDB queries

### ISSUE THREAD

**Issue by sezaru** [elixir-ecto/postgrex#504]
Hello, I'm using TimescaleDB extension for postgres, and one of the features is to disable/enable a table compression job, this is done with the following query:
`select alter_job_schedule(<job id>, next_start => 'infinity')`

I'm trying to run this inside Ecto/Postgrex, using this code:
```elixir
id = 1000
query = "select alter_job_schedule(#{id}, next_start => 'infinity')"

Ecto.Adapters.SQL.query!(Database.Exchanges.Binance.Repo, query)
```

The problem is that I get an `ArgumentError`, like this one:
```elixir
Bug Bug!! ** (ArgumentError) invalid Unix time 9224318721654775807
    (elixir 1.10.2) lib/calendar/datetime.ex:179: DateTime.from_unix!/3
    (postgrex 0.15.3) lib/postgrex/type_module.ex:897: Postgrex.DefaultTypes."Elixir.Postgrex.Extensions.TimestampTZ"/5
    (postgrex 0.15.3) lib/postgrex/type_module.ex:897: Postgrex.DefaultTypes."Elixir.Postgrex.Extensions.Record"/8
    (postgrex 0.15.3) lib/postgrex/protocol.ex:2869: Postgrex.Protocol.rows_recv/4
    (postgrex 0.15.3) lib/postgrex/protocol.ex:1898: Postgrex.Protocol.recv_execute/5
    (postgrex 0.15.3) lib/postgrex/protocol.ex:1735: Postgrex.Protocol.bind_execute_close/4
    (db_connection 2.2.1) lib/db_connection/holder.ex:316: DBConnection.Holder.holder_apply/4
    (db_connection 2.2.1) lib/db_connection.ex:1255: DBConnection.run_execute/5
iex(35) >>> 
13:51:08.227 [error] #PID<0.948.0> :gen_server "error_info/7" "gen_server.erl" 889 
↳ GenServer #PID<0.948.0> terminating
** (DBConnection.ConnectionError) client #PID<0.966.0> stopped: ** (ArgumentError) invalid Unix time 9224318721654775807
    (elixir 1.10.2) lib/calendar/datetime.ex:179: DateTime.from_unix!/3
    (postgrex 0.15.3) lib/postgrex/type_module.ex:897: Postgrex.DefaultTypes."Elixir.Postgrex.Extensions.TimestampTZ"/5
    (postgrex 0.15.3) lib/postgrex/type_module.ex:897: Postgrex.DefaultTypes."Elixir.Postgrex.Extensions.Record"/8
    (postgrex 0.15.3) lib/postgrex/protocol.ex:2869: Postgrex.Protocol.rows_recv/4
    (postgrex 0.15.3) lib/postgrex/protocol.ex:1898: Postgrex.Protocol.recv_execute/5
    (postgrex 0.15.3) lib/postgrex/protocol.ex:1735: Postgrex.Protocol.bind_execute_close/4
    (db_connection 2.2.1) lib/db_connection/holder.ex:316: DBConnection.Holder.holder_apply/4
    (db_connection 2.2.1) lib/db_connection.ex:1255: DBConnection.run_execute/5

    (db_connection 2.2.1) lib/db_connection/connection.ex:168: DBConnection.Connection.handle_cast/2
    (connection 1.0.4) lib/connection.ex:810: Connection.handle_async/3
    (stdlib 3.12) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib 3.12) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib 3.12) proc_lib.erl:259: :proc_lib.wake_up/3
Last message: {:"$gen_cast", {:stop, #Reference<0.214984589.2456682507.39276>, %DBConnection.ConnectionError{message: "client #PID<0.966.0> stopped: ** (ArgumentError) invalid Unix time 9224318721654775807\n    (elixir 1.10.2) lib/calendar/datetime.ex:179: DateTime.from_unix!/3\n    (postgrex 0.15.3) lib/postgrex/type_module.ex:897: Postgrex.DefaultTypes.\"Elixir.Postgrex.Extensions.TimestampTZ\"/5\n    (postgrex 0.15.3) lib/postgrex/type_module.ex:897: Postgrex.DefaultTypes.\"Elixir.Postgrex.Extensions.Record\"/8\n    (postgrex 0.15.3) lib/postgrex/protocol.ex:2869: Postgrex.Protocol.rows_recv/4\n    (postgrex 0.15.3) lib/postgrex/protocol.ex:1898: Postgrex.Protocol.recv_execute/5\n    (postgrex 0.15.3) lib/postgrex/protocol.ex:1735: Postgrex.Protocol.bind_execute_close/4\n    (db_connection 2.2.1) lib/db_connection/holder.ex:316: DBConnection.Holder.holder_apply/4\n    (db_connection 2.2.1) lib/db_connection.ex:1255: DBConnection.run_execute/5\n", severity: :error}, %Postgrex.Protocol{buffer: "", connection_id: 3359, connection_key: -940268481, disconnect_on_error_codes: [], null: nil, parameters: #Reference<0.214984589.2456551433.37928>, peer: {{127, 0, 0, 1}, 5432}, postgres: {:idle, #Reference<0.214984589.2456551435.39299>}, queries: #Reference<0.214984589.2456682508.37800>, sock: {:gen_tcp, #Port<0.1170>}, timeout: 300000, transactions: :naive, types: {Postgrex.DefaultTypes, #Reference<0.214984589.2456682508.37763>}}}}
State: {Postgrex.Protocol, %Postgrex.Protocol{buffer: "", connection_id: 3359, connection_key: -940268481, disconnect_on_error_codes: [], null: nil, parameters: #Reference<0.214984589.2456551433.37928>, peer: {{127, 0, 0, 1}, 5432}, postgres: {:idle, #Reference<0.214984589.2456551435.39299>}, queries: #Reference<0.214984589.2456682508.37800>, sock: {:gen_tcp, #Port<0.1170>}, timeout: 300000, transactions: :naive, types: {Postgrex.DefaultTypes, #Reference<0.214984589.2456682508.37763>}}}
```

Running the same query via psql returns this:
```
binance_dev=# select alter_job_schedule(1000, next_start => 'infinity');
                   alter_job_schedule                   
--------------------------------------------------------
 (1000,"3 days 12:00:00",00:00:00,-1,01:00:00,infinity)
(1 row)
```

It seems to me that the issue is this `9224318721654775807` number, I'm not sure where it came from, but it needs the `:nanosecond` options during `DateTime.from_unix!/3` to work (note that it does parse it but it give a nonsensical date).

**Comment by sezaru** [comment]
Just as a test, I replaced the line 50 `DateTime.from_unix!(microsecs + @us_epoch, :microsecond)` from `timestamptz.ex` with `nil` and now it returns this:
```elixir
%Postgrex.Result{
  columns: ["alter_job_schedule"],
  command: :select,
  connection_id: 5643,
  messages: [],
  num_rows: 1,
  rows: [
    [
      {1000, %Postgrex.Interval{days: 3, microsecs: 0, months: 0, secs: 43200},
       %Postgrex.Interval{days: 0, microsecs: 0, months: 0, secs: 0}, -1,
       %Postgrex.Interval{days: 0, microsecs: 0, months: 0, secs: 3600}, nil}
    ]
  ]
}
```

As you can see, it returns nil in the place of infinity.

So my guess is that Postgrex cannot parse infinity value correctly?

**Comment by josevalim** [comment]
According to Postgres wire protocol, the TImestampTZ is sent in microseconds. Looking at the error message, TimestampTZ is using the same type, but now in nanoseconds, without having any indication on the protocol that such change happened.

However, you can see that TimescaleDB is sending type as a record. So perhaps, if you write your custom Postgrex type, you can intercept the record and parse it using Timescale own rules. Otherwise, Postgrex is behaving as expected: a timestamptz is always in microsecond according to PG wire protocol - so there is nothing to fix on our side. Thanks!

**Comment by josevalim** [comment]
Oh, if the issue is only with infinity, then it does seem an encoding/decoding problem on our side. I am assuming infinity is always a fixed value, so we should be able to encode/decode it. We need to see how we handle infinity across the adapter though. For example, do we return `:infinity` for floats too?

**Comment by josevalim** [comment]
So, it seems we return `:inf` and `:"-inf"` for floats and we could do the same here too. Although I wonder if we should standardize on `:infinity` and `:"-infinity"` instead?

@ericmj do you recall if there is any reason why you didn't spell the full word?

**Comment by ericmj** [comment]
No, I don't exactly remember. I think I had seen erlang libraries use the three letter word when looking up how to handle infinity and nan in erlang.

**Comment by sezaru** [comment]
I was able to reproduce it without the TimescaleDB query, you can run this query to trigger it:
```elixir
Ecto.Adapters.SQL.query!(Repo, "select 'infinity'::timestamptz as value")
```

I also tried as:
```elixir
Ecto.Adapters.SQL.query!(Repo, "select 'infinity'::timestamp as value")
```
which gave me a similar error:
```elixir
(ArgumentError) cannot convert {{294277, 1, 9}, {4, 0, 54}} to naive datetime, reason: :invalid_date
```

Hope this can help somehow.
