### ISSUE TITLE
no function clause matching in Postgrex.Messages.parse/3

### ISSUE THREAD

**Issue by thelastinuit** [elixir-ecto/postgrex#561]
For some reason I can run `mix ecto.create` in `dev` and I have no issue.
But when I try it in `test`, I got the following:

```
22:37:52.248 [error] GenServer #PID<0.397.0> terminating
** (FunctionClauseError) no function clause matching in Postgrex.Messages.parse/3
    (postgrex 0.15.9) lib/postgrex/messages.ex:87: Postgrex.Messages.parse("8.0.25", 74, 6)
    (postgrex 0.15.9) lib/postgrex/protocol.ex:2996: Postgrex.Protocol.msg_decode/1
    (postgrex 0.15.9) lib/postgrex/protocol.ex:2965: Postgrex.Protocol.msg_recv/3
    (postgrex 0.15.9) lib/postgrex/protocol.ex:738: Postgrex.Protocol.auth_recv/3
    (postgrex 0.15.9) lib/postgrex/protocol.ex:629: Postgrex.Protocol.handshake/2
    (postgrex 0.15.9) lib/postgrex/protocol.ex:164: Postgrex.Protocol.connect_endpoints/6
    (db_connection 2.4.0) lib/db_connection/connection.ex:82: DBConnection.Connection.connect/2
    (connection 1.1.0) lib/connection.ex:622: Connection.enter_connect/5
Last message: nil
State: Postgrex.Protocol

22:37:52.277 [error] GenServer #PID<0.404.0> terminating
** (FunctionClauseError) no function clause matching in Postgrex.Messages.parse/3
    (postgrex 0.15.9) lib/postgrex/messages.ex:87: Postgrex.Messages.parse("8.0.25", 74, 6)
    (postgrex 0.15.9) lib/postgrex/protocol.ex:2996: Postgrex.Protocol.msg_decode/1
    (postgrex 0.15.9) lib/postgrex/protocol.ex:2965: Postgrex.Protocol.msg_recv/3
    (postgrex 0.15.9) lib/postgrex/protocol.ex:738: Postgrex.Protocol.auth_recv/3
    (postgrex 0.15.9) lib/postgrex/protocol.ex:629: Postgrex.Protocol.handshake/2
    (postgrex 0.15.9) lib/postgrex/protocol.ex:164: Postgrex.Protocol.connect_endpoints/6
    (db_connection 2.4.0) lib/db_connection/connection.ex:82: DBConnection.Connection.connect/2
    (connection 1.1.0) lib/connection.ex:622: Connection.enter_connect/5
Last message: nil
State: Postgrex.Protocol
** (Mix) The database for Ventupapi.Repo couldn't be created: killed
```

Any ideas?

Phoenix: 1.5.9
Elixir: 1.12.2
Erlang/OTP: 24

**Comment by josevalim** [comment]
What is your Postgres and Postgrex versions?

**Comment by thelastinuit** [comment]
> What is your Postgres and Postgrex versions?

Hey José, thanks for being the fastest man on the East.

- PostgreSQL: PostgreSQL 13.3 on x86_64-apple-darwin19.6.0, compiled by Apple clang version 11.0.3 (clang-1103.0.32.62), 64-bit
- Postgrex: 0.15.9

**Comment by thelastinuit** [comment]
You know after you requested the versions, I just noticed that it doesn't matter what version PostgreSQL is. By accident, I didn't have my postgres started, I tried to run the db creation and the same error happened. I would expected connection error or something hence my conclusion. So I guess I have something wrong with my Postgrex config? I have the normal setup and it does work in dev environment. weird.

**Comment by josevalim** [comment]
It may be that that your Postgres version is not allowing local connections or has tcp/udp protocols blocked? Check the available configs here: https://github.com/elixir-ecto/postgrex#contributing - if we can reproduce it, then we can also improve the error messages.

**Comment by thelastinuit** [comment]
Ok, I followed the contributing guide: made the proper changes to the hba file, restarted postgres and then run the test, this is the output:

```
❯ PGUSER=postgres PGPASSWORD=12341234 mix test
Excluding tags: [ssl: true]

..................................................
08:26:11.043 [info]  Postgrex.Protocol #PID<0.491.0> received unexpected message: {:tcp_closed, #Port<0.50>}
...............................................................................................................................................................................................................................................................

  1) test login cleartext password failure (LoginTest)
     test/login_test.exs:17
     Assertion failed, no matching message after 5000ms
     The following variables were pinned:
       pid = #PID<0.1941.0>
     The process mailbox is empty.
     code: assert_receive {:EXIT, ^pid, :killed}
     stacktrace:
       test/login_test.exs:293: LoginTest.assert_start_and_killed/1
       (ex_unit 1.12.2) lib/ex_unit/capture_log.ex:74: ExUnit.CaptureLog.capture_log/2
       test/login_test.exs:18: (test)

..

  2) test login scram password failure (LoginTest)
     test/login_test.exs:47
     Assertion failed, no matching message after 5000ms
     The following variables were pinned:
       pid = #PID<0.1959.0>
     The process mailbox is empty.
     code: assert_receive {:EXIT, ^pid, :killed}
     stacktrace:
       test/login_test.exs:293: LoginTest.assert_start_and_killed/1
       (ex_unit 1.12.2) lib/ex_unit/capture_log.ex:74: ExUnit.CaptureLog.capture_log/2
       test/login_test.exs:48: (test)

.................

  3) test login md5 password failure (LoginTest)
     test/login_test.exs:31
     Assertion failed, no matching message after 5000ms
     The following variables were pinned:
       pid = #PID<0.2050.0>
     The process mailbox is empty.
     code: assert_receive {:EXIT, ^pid, :killed}
     stacktrace:
       test/login_test.exs:293: LoginTest.assert_start_and_killed/1
       (ex_unit 1.12.2) lib/ex_unit/capture_log.ex:74: ExUnit.CaptureLog.capture_log/2
       test/login_test.exs:32: (test)

......
08:26:32.173 [info]  Application ssl exited: :stopped
...

Finished in 23.5 seconds (6.6s async, 16.8s sync)
2 doctests, 335 tests, 3 failures, 1 excluded
```

does that tell you something? That looks like the symbols in the Roswell crash. I hope it gives you a hint. @josevalim

**Comment by josevalim** [comment]
If the tests are passing then basic connection is working but it is weird that clear text nor md5 passwords are working.

**Comment by thelastinuit** [comment]
Ok, I can do whatever you want me to do. Just let me know how can I help. Right now, I'm lost.
Out of curiosity: `lib/postgrex/messages.ex:87: Postgrex.Messages.parse("8.0.25", 74, 6)` what's the module Messages trying to parse? I'm lost.

**Comment by thelastinuit** [comment]
@josevalim nvm... it was my stupidity all the way. in test, the port was not the right now. so in dev was the right port hence the nice functionality.
Very sorry in wasting your time, mea culpa.
