### ISSUE TITLE
ERROR 22021 (character_not_in_repertoire) for Emoji on Insert but not Update

### ISSUE THREAD

**Issue by inhji** [elixir-ecto/postgrex#594]
### Environment

* Elixir version (elixir -v): `Elixir 1.13.0 (compiled with Erlang/OTP 24)`
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): `psql (PostgreSQL) 12.9 (Ubuntu 12.9-0ubuntu0.20.04.1)`
* Ecto version (mix deps): `ecto 3.7.1`
* Database adapter and version (mix deps): `postgrex 0.16.1`
* Operating system: `elementary OS 6.1, based on Ubuntu 20.04.3 LTS`

### Current behavior

I have a table of notes, which include a title. If I create a new note and include an Emoji in the title, like `🥬 Savoy-Cabbage Casserole`,  postgrex raises this error: 

```
    ** (Postgrex.Error) ERROR 22021 (character_not_in_repertoire) invalid byte sequence for encoding "UTF8": 0x9f
        (ecto_sql 3.7.1) lib/ecto/adapters/sql.ex:760: Ecto.Adapters.SQL.raise_sql_call_error/1
        (ecto 3.7.1) lib/ecto/repo/schema.ex:744: Ecto.Repo.Schema.apply/4
        (ecto 3.7.1) lib/ecto/repo/schema.ex:367: anonymous fn/15 in Ecto.Repo.Schema.do_insert/4
        (emoji_test 0.1.0) lib/emoji_test_web/controllers/note_controller.ex:18: EmojiTestWeb.NoteController.create/2
        (emoji_test 0.1.0) lib/emoji_test_web/controllers/note_controller.ex:1: EmojiTestWeb.NoteController.action/2
        (emoji_test 0.1.0) lib/emoji_test_web/controllers/note_controller.ex:1: EmojiTestWeb.NoteController.phoenix_controller_pipeline/2
        (phoenix 1.6.6) lib/phoenix/router.ex:355: Phoenix.Router.__call__/2
        (emoji_test 0.1.0) lib/emoji_test_web/endpoint.ex:1: EmojiTestWeb.Endpoint.plug_builder_call/2
        (emoji_test 0.1.0) lib/plug/debugger.ex:136: EmojiTestWeb.Endpoint."call (overridable 3)"/2
        (emoji_test 0.1.0) lib/emoji_test_web/endpoint.ex:1: EmojiTestWeb.Endpoint.call/2
        (phoenix 1.6.6) lib/phoenix/endpoint/cowboy2_handler.ex:54: Phoenix.Endpoint.Cowboy2Handler.init/4
        (cowboy 2.9.0) /home/inhji/Devel/emoji_test/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
        (cowboy 2.9.0) /home/inhji/Devel/emoji_test/deps/cowboy/src/cowboy_stream_h.erl:306: :cowboy_stream_h.execute/3
        (cowboy 2.9.0) /home/inhji/Devel/emoji_test/deps/cowboy/src/cowboy_stream_h.erl:295: :cowboy_stream_h.request_process/3
        (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

If I create the note with a title like `Savoy-Cabbage Casserole`, ie. without the Emoji, the note gets created as expected. If I now update the note with the emoji title from above, the update succeeds.

I reproduced this behaviour with a new Project. I needed, I can upload it.

### Expected behavior

I was expecting the insert to accept the Emoji like the update does.

If you need any additional information, I'd be happy to provide it.

Thanks!

**Comment by inhji** [comment]
While going through the test project again, I realized that the error actually comes from Slugger, not postgrex: https://github.com/h4cc/slugger/issues/34
