### ISSUE TITLE
Support PostgreSQL 14 Infinity Values for NUMERIC <-> Decimal

### ISSUE THREAD

**Issue by davidarnold** [elixir-ecto/postgrex#605]
PostgreSQL 14 has added support for infinity values of the `NUMERIC` type.  Elixir also supports infinity values for `Decimal`, but Postgrex appears not to be able to map between them.

Versions: Postgrex 0.16.2, PostgreSQL 14.3

### Expected Results

```elixir
iex> Postgrex.query(conn, "SELECT NUMERIC 'Infinity'", [])
{:ok,
 %Postgrex.Result{
   columns: ["numeric"],
   command: :select,
   connection_id: 2847,
   messages: [],
   num_rows: 1,
   rows: [[#Decimal<Infinity>]]
 }}
```
```elixir
iex> Postgrex.query(conn, "SELECT NUMERIC '-Infinity'", [])
{:ok,
 %Postgrex.Result{
   columns: ["numeric"],
   command: :select,
   connection_id: 2847,
   messages: [],
   num_rows: 1,
   rows: [[#Decimal<-Infinity>]]
 }}
```

### Actual Results

```elixir
iex> Postgrex.query(conn, "SELECT NUMERIC 'Infinity'", [])
[error] GenServer #PID<0.420.0> terminating
** (DBConnection.ConnectionError) client #PID<0.457.0> stopped: ** (FunctionClauseError) no function clause matching in Postgrex.Extensions.Numeric.decode_sign/1
    (postgrex 0.16.2) lib/postgrex/extensions/numeric.ex:107: Postgrex.Extensions.Numeric.decode_sign(53248)
    (postgrex 0.16.2) lib/postgrex/extensions/numeric.ex:102: Postgrex.Extensions.Numeric.decode_numeric/5
    (postgrex 0.16.2) lib/postgrex/type_module.ex:947: Postgrex.DefaultTypes."Elixir.Postgrex.Extensions.Numeric"/6
    (postgrex 0.16.2) lib/postgrex/protocol.ex:3147: Postgrex.Protocol.rows_recv/4
    (postgrex 0.16.2) lib/postgrex/protocol.ex:2157: Postgrex.Protocol.recv_execute/5
    (postgrex 0.16.2) lib/postgrex/protocol.ex:1994: Postgrex.Protocol.bind_execute_close/4
    (db_connection 2.4.2) lib/db_connection/holder.ex:354: DBConnection.Holder.holder_apply/4
    (db_connection 2.4.2) lib/db_connection.ex:1364: DBConnection.run_execute/5
    (db_connection 2.4.2) lib/db_connection.ex:1459: DBConnection.run/6
    (db_connection 2.4.2) lib/db_connection.ex:595: DBConnection.parsed_prepare_execute/5
    (db_connection 2.4.2) lib/db_connection.ex:587: DBConnection.prepare_execute/4
    (postgrex 0.16.2) lib/postgrex.ex:333: Postgrex.query_prepare_execute/4
    (stdlib 4.0) erl_eval.erl:744: :erl_eval.do_apply/7
    (elixir 1.13.4) src/elixir.erl:296: :elixir.recur_eval/3
    (elixir 1.13.4) src/elixir.erl:274: :elixir.eval_forms/3
    (iex 1.13.4) lib/iex/evaluator.ex:310: IEx.Evaluator.handle_eval/3
    (iex 1.13.4) lib/iex/evaluator.ex:285: IEx.Evaluator.do_eval/3
    (iex 1.13.4) lib/iex/evaluator.ex:274: IEx.Evaluator.eval/3
    (iex 1.13.4) lib/iex/evaluator.ex:169: IEx.Evaluator.loop/1
    (iex 1.13.4) lib/iex/evaluator.ex:32: IEx.Evaluator.init/4

    (db_connection 2.4.2) lib/db_connection/connection.ex:198: DBConnection.Connection.handle_cast/2
    (connection 1.1.0) lib/connection.ex:810: Connection.handle_async/3
    (stdlib 4.0) gen_server.erl:1120: :gen_server.try_dispatch/4
    (stdlib 4.0) gen_server.erl:1197: :gen_server.handle_msg/6
    (stdlib 4.0) proc_lib.erl:250: :proc_lib.wake_up/3
Last message: {:"$gen_cast", {:stop, #Reference<0.1454003967.4157997057.79189>, %DBConnection.ConnectionError{message: "client #PID<0.457.0> stopped: ** (FunctionClauseError) no function clause matching in Postgrex.Extensions.Numeric.decode_sign/1\n    (postgrex 0.16.2) lib/postgrex/extensions/numeric.ex:107: Postgrex.Extensions.Numeric.decode_sign(53248)\n    (postgrex 0.16.2) lib/postgrex/extensions/numeric.ex:102: Postgrex.Extensions.Numeric.decode_numeric/5\n    (postgrex 0.16.2) lib/postgrex/type_module.ex:947: Postgrex.DefaultTypes.\"Elixir.Postgrex.Extensions.Numeric\"/6\n    (postgrex 0.16.2) lib/postgrex/protocol.ex:3147: Postgrex.Protocol.rows_recv/4\n    (postgrex 0.16.2) lib/postgrex/protocol.ex:2157: Postgrex.Protocol.recv_execute/5\n    (postgrex 0.16.2) lib/postgrex/protocol.ex:1994: Postgrex.Protocol.bind_execute_close/4\n    (db_connection 2.4.2) lib/db_connection/holder.ex:354: DBConnection.Holder.holder_apply/4\n    (db_connection 2.4.2) lib/db_connection.ex:1364: DBConnection.run_execute/5\n    (db_connection 2.4.2) lib/db_connection.ex:1459: DBConnection.run/6\n    (db_connection 2.4.2) lib/db_connection.ex:595: DBConnection.parsed_prepare_execute/5\n    (db_connection 2.4.2) lib/db_connection.ex:587: DBConnection.prepare_execute/4\n    (postgrex 0.16.2) lib/postgrex.ex:333: Postgrex.query_prepare_execute/4\n    (stdlib 4.0) erl_eval.erl:744: :erl_eval.do_apply/7\n    (elixir 1.13.4) src/elixir.erl:296: :elixir.recur_eval/3\n    (elixir 1.13.4) src/elixir.erl:274: :elixir.eval_forms/3\n    (iex 1.13.4) lib/iex/evaluator.ex:310: IEx.Evaluator.handle_eval/3\n    (iex 1.13.4) lib/iex/evaluator.ex:285: IEx.Evaluator.do_eval/3\n    (iex 1.13.4) lib/iex/evaluator.ex:274: IEx.Evaluator.eval/3\n    (iex 1.13.4) lib/iex/evaluator.ex:169: IEx.Evaluator.loop/1\n    (iex 1.13.4) lib/iex/evaluator.ex:32: IEx.Evaluator.init/4\n", reason: :error, severity: :error}, %Postgrex.Protocol{buffer: "", connection_id: 2840, connection_key: 1835489823, disconnect_on_error_codes: [], null: nil, parameters: #Reference<0.1454003967.4157603842.246632>, peer: {{127, 0, 0, 1}, 15432}, ping_timeout: 15000, postgres: {:idle, #Reference<0.1454003967.4157865985.79197>}, queries: #Reference<0.1454003967.4157734920.245661>, sock: {:gen_tcp, #Port<0.11>}, timeout: 15000, transactions: :naive, types: {Postgrex.DefaultTypes, #Reference<0.1454003967.4157734914.246487>}}}}
State: {Postgrex.Protocol, %Postgrex.Protocol{buffer: "", connection_id: 2840, connection_key: 1835489823, disconnect_on_error_codes: [], null: nil, parameters: #Reference<0.1454003967.4157603842.246632>, peer: {{127, 0, 0, 1}, 15432}, ping_timeout: 15000, postgres: {:idle, #Reference<0.1454003967.4157865985.79197>}, queries: #Reference<0.1454003967.4157734920.245661>, sock: {:gen_tcp, #Port<0.11>}, timeout: 15000, transactions: :naive, types: {Postgrex.DefaultTypes, #Reference<0.1454003967.4157734914.246487>}}}                                                                                                                                                            
** (FunctionClauseError) no function clause matching in Postgrex.Extensions.Numeric.decode_sign/1    
    
    The following arguments were given to Postgrex.Extensions.Numeric.decode_sign/1:
    
        # 1
        53248
    
    Attempted function clauses (showing 2 out of 2):
    
        defp decode_sign(0)
        defp decode_sign(16384)
    
    (postgrex 0.16.2) lib/postgrex/extensions/numeric.ex:107: Postgrex.Extensions.Numeric.decode_sign/1
    (postgrex 0.16.2) lib/postgrex/extensions/numeric.ex:102: Postgrex.Extensions.Numeric.decode_numeric/5
    (postgrex 0.16.2) lib/postgrex/type_module.ex:947: Postgrex.DefaultTypes."Elixir.Postgrex.Extensions.Numeric"/6
    (postgrex 0.16.2) lib/postgrex/protocol.ex:3147: Postgrex.Protocol.rows_recv/4
    (postgrex 0.16.2) lib/postgrex/protocol.ex:2157: Postgrex.Protocol.recv_execute/5
    (postgrex 0.16.2) lib/postgrex/protocol.ex:1994: Postgrex.Protocol.bind_execute_close/4
    (db_connection 2.4.2) lib/db_connection/holder.ex:354: DBConnection.Holder.holder_apply/4
    (db_connection 2.4.2) lib/db_connection.ex:1364: DBConnection.run_execute/5
    (db_connection 2.4.2) lib/db_connection.ex:1459: DBConnection.run/6
    (db_connection 2.4.2) lib/db_connection.ex:595: DBConnection.parsed_prepare_execute/5
    (db_connection 2.4.2) lib/db_connection.ex:587: DBConnection.prepare_execute/4
    (postgrex 0.16.2) lib/postgrex.ex:333: Postgrex.query_prepare_execute/4
```
```elixir
iex> Postgrex.query(conn, "SELECT NUMERIC '-Infinity'", [])
[error] GenServer #PID<0.417.0> terminating
** (DBConnection.ConnectionError) client #PID<0.457.0> stopped: ** (FunctionClauseError) no function clause matching in Postgrex.Extensions.Numeric.decode_sign/1
    (postgrex 0.16.2) lib/postgrex/extensions/numeric.ex:107: Postgrex.Extensions.Numeric.decode_sign(61440)
    (postgrex 0.16.2) lib/postgrex/extensions/numeric.ex:102: Postgrex.Extensions.Numeric.decode_numeric/5
    (postgrex 0.16.2) lib/postgrex/type_module.ex:947: Postgrex.DefaultTypes."Elixir.Postgrex.Extensions.Numeric"/6
    (postgrex 0.16.2) lib/postgrex/protocol.ex:3147: Postgrex.Protocol.rows_recv/4
    (postgrex 0.16.2) lib/postgrex/protocol.ex:2157: Postgrex.Protocol.recv_execute/5
    (postgrex 0.16.2) lib/postgrex/protocol.ex:1994: Postgrex.Protocol.bind_execute_close/4
    (db_connection 2.4.2) lib/db_connection/holder.ex:354: DBConnection.Holder.holder_apply/4
    (db_connection 2.4.2) lib/db_connection.ex:1364: DBConnection.run_execute/5
    (db_connection 2.4.2) lib/db_connection.ex:1459: DBConnection.run/6
    (db_connection 2.4.2) lib/db_connection.ex:595: DBConnection.parsed_prepare_execute/5
    (db_connection 2.4.2) lib/db_connection.ex:587: DBConnection.prepare_execute/4
    (postgrex 0.16.2) lib/postgrex.ex:333: Postgrex.query_prepare_execute/4
    (stdlib 4.0) erl_eval.erl:744: :erl_eval.do_apply/7
    (elixir 1.13.4) src/elixir.erl:296: :elixir.recur_eval/3
    (elixir 1.13.4) src/elixir.erl:274: :elixir.eval_forms/3
    (iex 1.13.4) lib/iex/evaluator.ex:310: IEx.Evaluator.handle_eval/3
    (iex 1.13.4) lib/iex/evaluator.ex:285: IEx.Evaluator.do_eval/3
    (iex 1.13.4) lib/iex/evaluator.ex:274: IEx.Evaluator.eval/3
    (iex 1.13.4) lib/iex/evaluator.ex:169: IEx.Evaluator.loop/1
    (iex 1.13.4) lib/iex/evaluator.ex:32: IEx.Evaluator.init/4

    (db_connection 2.4.2) lib/db_connection/connection.ex:198: DBConnection.Connection.handle_cast/2
    (connection 1.1.0) lib/connection.ex:810: Connection.handle_async/3
    (stdlib 4.0) gen_server.erl:1120: :gen_server.try_dispatch/4
    (stdlib 4.0) gen_server.erl:1197: :gen_server.handle_msg/6
    (stdlib 4.0) proc_lib.erl:250: :proc_lib.wake_up/3
Last message: {:"$gen_cast", {:stop, #Reference<0.1454003967.4157734914.258305>, %DBConnection.ConnectionError{message: "client #PID<0.457.0> stopped: ** (FunctionClauseError) no function clause matching in Postgrex.Extensions.Numeric.decode_sign/1\n    (postgrex 0.16.2) lib/postgrex/extensions/numeric.ex:107: Postgrex.Extensions.Numeric.decode_sign(61440)\n    (postgrex 0.16.2) lib/postgrex/extensions/numeric.ex:102: Postgrex.Extensions.Numeric.decode_numeric/5\n    (postgrex 0.16.2) lib/postgrex/type_module.ex:947: Postgrex.DefaultTypes.\"Elixir.Postgrex.Extensions.Numeric\"/6\n    (postgrex 0.16.2) lib/postgrex/protocol.ex:3147: Postgrex.Protocol.rows_recv/4\n    (postgrex 0.16.2) lib/postgrex/protocol.ex:2157: Postgrex.Protocol.recv_execute/5\n    (postgrex 0.16.2) lib/postgrex/protocol.ex:1994: Postgrex.Protocol.bind_execute_close/4\n    (db_connection 2.4.2) lib/db_connection/holder.ex:354: DBConnection.Holder.holder_apply/4\n    (db_connection 2.4.2) lib/db_connection.ex:1364: DBConnection.run_execute/5\n    (db_connection 2.4.2) lib/db_connection.ex:1459: DBConnection.run/6\n    (db_connection 2.4.2) lib/db_connection.ex:595: DBConnection.parsed_prepare_execute/5\n    (db_connection 2.4.2) lib/db_connection.ex:587: DBConnection.prepare_execute/4\n    (postgrex 0.16.2) lib/postgrex.ex:333: Postgrex.query_prepare_execute/4\n    (stdlib 4.0) erl_eval.erl:744: :erl_eval.do_apply/7\n    (elixir 1.13.4) src/elixir.erl:296: :elixir.recur_eval/3\n    (elixir 1.13.4) src/elixir.erl:274: :elixir.eval_forms/3\n    (iex 1.13.4) lib/iex/evaluator.ex:310: IEx.Evaluator.handle_eval/3\n    (iex 1.13.4) lib/iex/evaluator.ex:285: IEx.Evaluator.do_eval/3\n    (iex 1.13.4) lib/iex/evaluator.ex:274: IEx.Evaluator.eval/3\n    (iex 1.13.4) lib/iex/evaluator.ex:169: IEx.Evaluator.loop/1\n    (iex 1.13.4) lib/iex/evaluator.ex:32: IEx.Evaluator.init/4\n", reason: :error, severity: :error}, %Postgrex.Protocol{buffer: "", connection_id: 2845, connection_key: -1286704763, disconnect_on_error_codes: [], null: nil, parameters: #Reference<0.1454003967.4157603848.245689>, peer: {{127, 0, 0, 1}, 15432}, ping_timeout: 15000, postgres: {:idle, #Reference<0.1454003967.4157603842.258313>}, queries: #Reference<0.1454003967.4157734920.245686>, sock: {:gen_tcp, #Port<0.14>}, timeout: 15000, transactions: :naive, types: {Postgrex.DefaultTypes, #Reference<0.1454003967.4157734914.246487>}}}}
State: {Postgrex.Protocol, %Postgrex.Protocol{buffer: "", connection_id: 2845, connection_key: -1286704763, disconnect_on_error_codes: [], null: nil, parameters: #Reference<0.1454003967.4157603848.245689>, peer: {{127, 0, 0, 1}, 15432}, ping_timeout: 15000, postgres: {:idle, #Reference<0.1454003967.4157603842.258313>}, queries: #Reference<0.1454003967.4157734920.245686>, sock: {:gen_tcp, #Port<0.14>}, timeout: 15000, transactions: :naive, types: {Postgrex.DefaultTypes, #Reference<0.1454003967.4157734914.246487>}}}                                                                                                                                                      
** (FunctionClauseError) no function clause matching in Postgrex.Extensions.Numeric.decode_sign/1    
    
    The following arguments were given to Postgrex.Extensions.Numeric.decode_sign/1:
    
        # 1
        61440
    
    Attempted function clauses (showing 2 out of 2):
    
        defp decode_sign(0)
        defp decode_sign(16384)
    
    (postgrex 0.16.2) lib/postgrex/extensions/numeric.ex:107: Postgrex.Extensions.Numeric.decode_sign/1
    (postgrex 0.16.2) lib/postgrex/extensions/numeric.ex:102: Postgrex.Extensions.Numeric.decode_numeric/5
    (postgrex 0.16.2) lib/postgrex/type_module.ex:947: Postgrex.DefaultTypes."Elixir.Postgrex.Extensions.Numeric"/6
    (postgrex 0.16.2) lib/postgrex/protocol.ex:3147: Postgrex.Protocol.rows_recv/4
    (postgrex 0.16.2) lib/postgrex/protocol.ex:2157: Postgrex.Protocol.recv_execute/5
    (postgrex 0.16.2) lib/postgrex/protocol.ex:1994: Postgrex.Protocol.bind_execute_close/4
    (db_connection 2.4.2) lib/db_connection/holder.ex:354: DBConnection.Holder.holder_apply/4
    (db_connection 2.4.2) lib/db_connection.ex:1364: DBConnection.run_execute/5
    (db_connection 2.4.2) lib/db_connection.ex:1459: DBConnection.run/6
    (db_connection 2.4.2) lib/db_connection.ex:595: DBConnection.parsed_prepare_execute/5
    (db_connection 2.4.2) lib/db_connection.ex:587: DBConnection.prepare_execute/4
    (postgrex 0.16.2) lib/postgrex.ex:333: Postgrex.query_prepare_execute/4
```

**Comment by josevalim** [comment]
PRs are welcome!

**Comment by davidarnold** [comment]
PR #606 is working in my application tests!
