### ISSUE TITLE
(FunctionClauseError) no function clause matching in Postgrex.Protocol.handle_msg/3

### ISSUE THREAD

**Issue by benonymus** [elixir-ecto/postgrex#647]
### Elixir version

1.14.3

### Database and Version

Postgresql 15

### Postgrex Version

 0.16.5

### Current behavior

Hey,

I am trying to use https://www.polyscale.ai/ with my elixir application.

It works in a simple elixir application, but there are deps that break, like Oban, or FunWithFlags and something else too but I couldn't pinpoint it.

The only trace that I see is this: 

```
[error] GenServer #PID<0.1093.0> terminating
** (DBConnection.ConnectionError) client #PID<0.1389.0> stopped: ** (FunctionClauseError) no function clause matching in Postgrex.Protocol.handle_msg/3
    (postgrex 0.16.5) lib/postgrex/protocol.ex:3267: Postgrex.Protocol.handle_msg(%Postgrex.Protocol{sock: {:ssl, {:sslsocket, {:gen_tcp, #Port<0.34>, :tls_connection, :undefined}, [#PID<0.1112.0>, #PID<0.1111.0>]}}, connection_id: -1337895193, connection_key: 756839344, peer: {{34, 124, 250, 180}, 5432}, types: {Postgrex.DefaultTypes, #Reference<0.3522207158.2402942979.255103>}, null: nil, timeout: 15000, ping_timeout: 15000, parameters: #Reference<0.3522207158.2402811907.255253>, queries: #Reference<0.3522207158.2402942979.255249>, postgres: :idle, transactions: :naive, buffer: "", disconnect_on_error_codes: []}, %{messages: [], mode: :transaction, notify: #Function<11.40058566/2 in Postgrex.Protocol.notify/1>, prepare: false}, {:msg_parse_complete})
    (postgrex 0.16.5) lib/postgrex/protocol.ex:2902: Postgrex.Protocol.recv_close/3
    (postgrex 0.16.5) lib/postgrex/protocol.ex:1460: Postgrex.Protocol.close_parse_describe_flush/3
    (db_connection 2.4.3) lib/db_connection/holder.ex:354: DBConnection.Holder.holder_apply/4
    (db_connection 2.4.3) lib/db_connection.ex:1398: DBConnection.prepare/4
    (db_connection 2.4.3) lib/db_connection.ex:1391: DBConnection.run_prepare/4
    (db_connection 2.4.3) lib/db_connection.ex:1403: DBConnection.run_prepare_execute/5
    (db_connection 2.4.3) lib/db_connection.ex:1508: DBConnection.run/6

    (db_connection 2.4.3) lib/db_connection/connection.ex:198: DBConnection.Connection.handle_cast/2
    (connection 1.1.0) lib/connection.ex:810: Connection.handle_async/3
    (stdlib 4.3) gen_server.erl:1123: :gen_server.try_dispatch/4
    (stdlib 4.3) gen_server.erl:1200: :gen_server.handle_msg/6
    (stdlib 4.3) proc_lib.erl:250: :proc_lib.wake_up/3
Last message: {:"$gen_cast", {:stop, #Reference<0.3522207158.2402942979.255256>, %DBConnection.ConnectionError{message: "client #PID<0.1389.0> stopped: ** (FunctionClauseError) no function clause matching in Postgrex.Protocol.handle_msg/3\n    (postgrex 0.16.5) lib/postgrex/protocol.ex:3267: Postgrex.Protocol.handle_msg(%Postgrex.Protocol{sock: {:ssl, {:sslsocket, {:gen_tcp, #Port<0.34>, :tls_connection, :undefined}, [#PID<0.1112.0>, #PID<0.1111.0>]}}, connection_id: -1337895193, connection_key: 756839344, peer: {{34, 124, 250, 180}, 5432}, types: {Postgrex.DefaultTypes, #Reference<0.3522207158.2402942979.255103>}, null: nil, timeout: 15000, ping_timeout: 15000, parameters: #Reference<0.3522207158.2402811907.255253>, queries: #Reference<0.3522207158.2402942979.255249>, postgres: :idle, transactions: :naive, buffer: \"\", disconnect_on_error_codes: []}, %{messages: [], mode: :transaction, notify: #Function<11.40058566/2 in Postgrex.Protocol.notify/1>, prepare: false}, {:msg_parse_complete})\n    (postgrex 0.16.5) lib/postgrex/protocol.ex:2902: Postgrex.Protocol.recv_close/3\n    (postgrex 0.16.5) lib/postgrex/protocol.ex:1460: Postgrex.Protocol.close_parse_describe_flush/3\n    (db_connection 2.4.3) lib/db_connection/holder.ex:354: DBConnection.Holder.holder_apply/4\n    (db_connection 2.4.3) lib/db_connection.ex:1398: DBConnection.prepare/4\n    (db_connection 2.4.3) lib/db_connection.ex:1391: DBConnection.run_prepare/4\n    (db_connection 2.4.3) lib/db_connection.ex:1403: DBConnection.run_prepare_execute/5\n    (db_connection 2.4.3) lib/db_connection.ex:1508: DBConnection.run/6\n", severity: :error, reason: :error}, %Postgrex.Protocol{sock: {:ssl, {:sslsocket, {:gen_tcp, #Port<0.34>, :tls_connection, :undefined}, [#PID<0.1112.0>, #PID<0.1111.0>]}}, connection_id: -1337895193, connection_key: 756839344, peer: {{34, 124, 250, 180}, 5432}, types: {Postgrex.DefaultTypes, #Reference<0.3522207158.2402942979.255103>}, null: nil, timeout: 15000, ping_timeout: 15000, parameters: #Reference<0.3522207158.2402811907.255253>, queries: #Reference<0.3522207158.2402942979.255249>, postgres: :idle, transactions: :naive, buffer: "", disconnect_on_error_codes: []}}}
State: {Postgrex.Protocol, %Postgrex.Protocol{sock: {:ssl, {:sslsocket, {:gen_tcp, #Port<0.34>, :tls_connection, :undefined}, [#PID<0.1112.0>, #PID<0.1111.0>]}}, connection_id: -1337895193, connection_key: 756839344, peer: {{34, 124, 250, 180}, 5432}, types: {Postgrex.DefaultTypes, #Reference<0.3522207158.2402942979.255103>}, null: nil, timeout: 15000, ping_timeout: 15000, parameters: #Reference<0.3522207158.2402811907.255253>, queries: #Reference<0.3522207158.2402942979.255249>, postgres: :idle, transactions: :naive, buffer: "", disconnect_on_error_codes: []}}

```

I looked at the args that come to the function, and the problem seems to be the last one `{:msg_parse_complete}`.

Any idea why this happens? 

Thank you

### Expected behavior

Ideally these connections would be happy with the setup as the regular repo calls seem to be.

**Comment by greg-rychlewski** [comment]
Hi @benonymus,

Thank you for reporting. I never heard of https://www.polyscale.ai/, is it basically a database that accepts the Postgres wire protocol?

The issue is happening because the function here: `close_parse_describe_flush` is first sending a close message and then the parse/describe messages. 

By the Postgres protocol we are supposed to receive a `CloseComplete` message or an error if it is not closed properly. But it is not coming back and skipping right ahead to the parse response.

Is this something you could report upstream?

**Comment by benonymus** [comment]
Hey @greg-rychlewski,

Thanks a lot for checking this!

I am in contact with the team at Polyscale and I will let them know!

**Comment by benjamg** [comment]
Thanks for taking the time in finding this.
PolyScale is a caching frontend that accepts the PostgreSQL wire protocol rather than a database in it's own right and this was indeed a bug in my code due to the way I was trying to avoid a round-trip to the database wherever possible, knowing it was a missing CloseComplete helped me hunt down the flaw :)
